### ISSUE TITLE
"Catkin" referenced in quick start?

### ISSUE THREAD

**Issue by ablakey** [colcon/colcon-core#103]
In the TL;DR section a number of commands reference `catkin`. Is this accurate? It looks like they should be referencing `colcon`

https://colcon.readthedocs.io/en/latest/user/quick-start.html

**Comment by sloretz** [comment]
Good catch, looks like those should be `colcon test` and `colcon test-result --all`. Would you mind opening a PR on https://github.com/colcon/colcon.readthedocs.org ?

**Comment by dirk-thomas** [comment]
Addressed in colcon/colcon.readthedocs.org#32.
