### ISSUE TITLE
Convert PackageDescriptor.dependencies into an object so metadata can be attached.

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-core#106]
This work needs to be done to support colcon/colcon-ros#39.

Based on my initial investigation the following packages are affected:

* colcon-core #116
* ~~colcon-package-information~~
* ~~colcon-package-selection~~
* ~~colcon-parallel-executor~~
* ~~colcon-cargo~~
* ~~colcon-bazel~~
* ~~colcon-ros-bazel~~
* ~~colcon-cmake~~
* colcon-ros colcon/colcon-ros#40
* colcon-python-setup-py colcon/colcon-python-setup-py#11
* ~~colcon-gradle~~
* ~~colcon-ros-grade~~
* ~~colcon-powershell~~
* ~~colcon-graphviz-anim~~

I will start with colcon-core so we can settle on the API and usage and then follow up with PRs for all affected packages.

**Comment by dirk-thomas** [comment]
I am wondering if it is necessary / useful to update all the packages which don't have any metadata or if we should just close those and let them keep adding plain `str` dependency names?

**Comment by murphm8** [comment]
I think they can be closed for now, and if at some point those packages want to add metadata then that can be done in a PR with the metadata addition. 

Do you think the guidance from now on should be to use DependencyDescriptor?
Should consumers of dependencies that need the metadata just always verify the dependency is a DependencyDescriptor?

**Comment by dirk-thomas** [comment]
We recently changed our bootstrap repo which contains all the Python packages so I am not 100% confident to do it now (with others not available) if something goes wrong. But I will aim to ship a new release of `colcon-core` on Monday.

**Comment by dirk-thomas** [comment]
I am still blocked by problems with our bootstrap repo. I will comment here as soon as I was able to do a release... :disappointed:

**Comment by dirk-thomas** [comment]
`colcon-core` 0.3.10 has just been released. Sorry for the delay. Please update the remaining PRs to include that version dependency - their CI should then pass and be mergable.

**Comment by murphm8** [comment]
Awesome, thanks for getting these changes shipped! Everything for this ticket is completed. Will close it.
