### ISSUE TITLE
Spell check test broken on Bionic (and others)

### ISSUE THREAD

**Issue by cottsay** [colcon/colcon-core#112]
I'm not sure why (yet), but `test_spell_check` appears to fail on Bionic and Fedora 29. Seems to be running (and passing) on Travis, though.

The console output is much too long to paste in here, but after installing `python3-enchant`, pytest breaks on this test every time.

For now, I'm going to skip this test for Fedora packaging since it appears broken on Ubuntu as well, but I wanted to file an issue to follow-up on this later.

**Comment by dirk-thomas** [comment]
Yeah, the dictionary shipped with various Ubuntu versions is different. I haven't found a good way to get deterministic results. Any ideas are welcome :wink:

**Comment by cottsay** [comment]
#114 will get the tests passing for now, but it isn't a solution. Enchant 2 has a mechanism for supporting local configurations, but Bionic doesn't have Enchant 2. For Travis specifically, we could modify the "user" dictionary, but that doesn't really give us much over the existing solution.

Beyond continuing with the current approach (which *is* working), the only thing I can think of is either bundling or downloading a common dictionary instead of relying on the distribution-provided one...

**Comment by cottsay** [comment]
Okay, this is a little deeper than I thought. Somehow, setting `filterwarnings` to `error` is causing the spellcheck test to pass. Removing the error mode from `DeprecationWarning` (either default or ignore) makes the test fail. I think this may be a bug in pylint or astroid, and I think Fedora rawhide has the fix, because it fails in the same way Bionic does when I remove the error mode as described.

In any case, there are quite a few additional tokens (namely ones currently in backticks in comments) that would need to be added to get things passing in Fedora rawhide.
