### ISSUE TITLE
Colcon dry run

### ISSUE THREAD

**Issue by johnmarkwayve** [colcon/colcon-core#113]
We're using bazel as our build system, which to build ROS calls into colcon. Unfortunately, bazel likes to know a complete list of files that will be generated ahead-of-time. Right now, my workaround is to build once, inspect the files created, then give that list to bazel so it can manage builds from now on.

I'd love to streamline this process. In particular, it would be ideal if there was a way to get colcon to do a "dry run", and report what files it _would_ create, without actually doing the builds. Is this currently possible? Or a possible feature? I'm happy to help with implementation if it's not a huge amount of work.

**Comment by johnmarkwayve** [comment]
Oh, while I'm here, a clean shortcut for "don't write any logs" would be lovely (and hopefully easy?). I tried `COLCON_LOG_PATH=/dev/null`, but it didn't like that. I guess I could manually disable all of the event handlers, but it a shortcut would be neater.

**Comment by dirk-thomas** [comment]
If you are invoking `colcon` from within `bazel` I assume you are still relying on each packages `CMakeLists.txt` / `setuptools` logic to build the package? Afaik e.g. CMake doesn't offer anything like a "dry run". While you could introspect the generated `Makefile` (assuming only non-Windows is targeted) even the CMake configure phase could already generate arbitrary files and I doubt that is introspectable. So I don't see how what you want to do is possible (but as a disclaimer: I have no experience with bazel).

**Comment by dirk-thomas** [comment]
> a clean shortcut for "don't write any logs" would be lovely (and hopefully easy?).
> I guess I could manually disable all of the event handlers, but it a shortcut would be neater.

You could create a "mixin" which disables all the event handlers which perform logging. Then you could trigger the behavior with `--mixin dont-write-any-logs` (see https://github.com/colcon/colcon-mixin and https://github.com/colcon/colcon-mixin-repository).

Implementing special logic to support something like `COLCON_LOG_PATH=/dev/null` should be easy but I would wonder how that should work cross platform. Therefore I think the mixin is the easier / cleaner / more uniform / easier to document approach.

Please keep the conversation in an issue on topic since off topic questions like this (not related to the dry run question) are likely to get lost / missed and are hard to find in the future.

**Comment by johnmarkwayve** [comment]
Thanks for your replies.

Sounds like the "dry run" is probably a no-go. Given that the ROS2 build setup is so complicated and distributed across many repositories, you're right, I'm treating it like a black-box that I'm trying to run as close to how you would from the terminal as possible. There are two big differences: ideally bazel would like _all_ dependencies (tools, compilers, system dependencies) explicitly listed, and bazel often needs _all_ output files known ahead of time.

I'm not close to reaching the first goal, but I've come enough of the way for now. As for the second, the current workaround is exceedingly ugly, since ROS's `build` and `install` directories are huge and contain symlinks to each other (I think I even found one back to the `src` directory at some point). The result is my bazel build file has lists with thousands of files that bazel may at some point want to know about.

Broadly, the problem is that bazel is quite an opinionated build system, and ROS2 is a very large and diverse code base with a very permissive and decentralised build setup. Getting the two to play nicely hasn't been the most fun.

Feel free to close this issue if it's a non-starter.


You're right, the no-logs was a throwaway comment that doesn't belong here.

**Comment by dirk-thomas** [comment]
> the current workaround is exceedingly ugly, since ROS's build and install directories are huge and contain symlinks to each other

If you don't use the option `--symlink-install` I don't see why there would be any symlink in the `install`. You should actually be able to delete the `src` and `build` and then `install` should still be self contained and relocatable (that is ultimately what the Debian packages are). Can you share which exact files where symlinks in your case?

> the problem is that bazel is quite an opinionated build system, and ROS2 is a very large and diverse code base with a very permissive and decentralised build setup. Getting the two to play nicely hasn't been the most fun.

Indeed :+1:

> Feel free to close this issue if it's a non-starter.

I will go ahead and do that since I don't see what `colcon` could do atm. Please feel free to post more information and this can be reopened if it is more clear what should be done to support this case better.

**Comment by johnmarkwayve** [comment]
> Can you share which exact files where symlinks in your case?

IIRC there were at least some symlinks to python scripts back in `src/` that were needed if you wanted to build additional ROS packages having already `source`d the main ROS `install/local_setup.*`. Though I don't seem to be able to find them now. I'll post again if I discover them again (or my memory improves).

**Comment by clalancette** [comment]
@johnmarkwayve In the past I also spent a bit of time getting the ROS build tools and bazel working together.  The easiest thing to do in that case was to use the ROS build tools as the top-level build tools, and have them call into Bazel.  The big mismatch then is that Bazel doesn't really have the 'install' target that colcon expects.  However, this can be worked around by making a custom install target for Bazel (see [Drake](https://github.com/RobotLocomotion/drake) for one example on how to do this).

Depending on your setup and the developer experience you want, this may or may not work for you.  But if you have a small set of ROS packages to build, and your custom code is a Bazel repository with an install target, I found that this setup actually works quite well.  Food for thought.

**Comment by johnmarkwayve** [comment]
@clalancette Thanks, for the suggestion. It's something we thought about as well. The thing is, we have a large a diverse monorepo. ROS2 is used for several components, but they are each relatively small compared to the whole, often targeting different architectures/OSs. Forcing the whole project to use colcon just because ROS2 has a idiosyncratic build setup felt somewhat backward, not to mention the that a battle-tested incremental build system (with remote caching and the like) is only going to become more important as the monorepo grows. It's just not a scalable solution for us where ROS2 is a dependency, not a platform.
