### ISSUE TITLE
Log file conflicts when running colcon with parallel and COLCON_LOG_PATH variable set

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-core#129]
I'm running multiple `colcon build` executions using the `paralell` tool. When I have COLCON_LOG_PATH set I get the error:

    Traceback (most recent call last):
      File "/usr/local/bin/colcon", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.5/dist-packages/colcon_core/command.py", line 127, in main
        create_log_path(args.verb_name)
      File "/usr/local/lib/python3.5/dist-packages/colcon_core/location.py", line 146, in create_log_path
        path, path.parent / 'latest_{verb_name}'.format_map(locals()))
      File "/usr/local/lib/python3.5/dist-packages/colcon_core/location.py", line 171, in _create_symlink
        os.symlink(str(src), str(dst))
     FileExistsError: [Errno 17] File exists: 'build_2018-11-02_20-22-42' -> '/workspace/build/private/logs/latest_build'

This is because both instances of my `colcon build` command are trying to write to the same `latest_build` folder. Is this a supported use case?

**Comment by dirk-thomas** [comment]
> using the `paralell` tool

What kind of tool is that?

> This is because both instances of my `colcon build` command are trying to write to the same `latest_build` folder.

Each invocation will only write to the specific directory with the timestamp. So invoking the tool with the same verb at the same second is currently indeed a problem. I don't think that is your problem though.

The `latest*` symlinks are only created for the user for convenience. There could be a race condition if two invocations run through the same logic with checking and then creating the symlink.

Can you please provide a reproducible example.

**Comment by dirk-thomas** [comment]
Please try #130 which makes sure that each invocation gets a separate log directory and all FS calls which might be subject to a race are handling exceptions gracefully.

**Comment by murphm8** [comment]
I'm using https://www.gnu.org/software/parallel/

The command is:

    parallel < commands.txt

The contents of commands.txt is:

    colcon build --base-paths ./workspace1 --build-base ./build/robot/build-output --install-base ./build/private/robot/install-output
    colcon build --base-paths ./workspace2 --build-base ./build/simulation/build-output --install-base ./build/private/simulation/install-output

The environment has COLCON_LOG_PATH set to /home/<user>/build/logs.

**Comment by dirk-thomas** [comment]
I can't make it fail with similar commands (e.g. building a ROS 2 workspace twice in parallel). Maybe it is related to your filesystem? Mine is on a SSD which will be less likely to run into a race condition due to its speed.

Please try #130 since it clearly separates your two log directories. Please comment here with your results.

**Comment by murphm8** [comment]
I successfully ran the build in parallel with your changes. Thanks for the solution!
