### ISSUE TITLE
Cannot find requisite cpp files for setuptools

### ISSUE THREAD

**Issue by RitwikGupta** [colcon/colcon-core#135]
In `src/xlib/`, I have a setup.py which is build a Python C++ extension using setuptools. When `python3 setup.py build_ext` is run within that directory, the build completes successfully. However, when running `colcon build --symlink-install` from the workspace root, I get the following errors:
```
x86_64-linux-gnu-gcc: error: PythonBindings.cpp: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
---
```
It seems that colcon is not copying over the source files to the build folder at `build/xlib`, and thus the setup.py is unable to build the extension. I am unable to find documentation or sources to help me do this.

`colcon build` completes successfully, but obviously leaves the built `xlib.cpython-*-.so` in the `src/xlib` folder.

```python
sources=[
        'PythonBindings.cpp',
        'Other.cpp',
        'Example.cpp'
]
lib_module = Extension(
    'xlib',
    sources=sources,
    language='C++',
    extra_compile_args=['-std=c++14'],
    libraries=['stdc++'],
    include_dirs=[numpy.get_include(), get_python_inc()]
)

setup(
    name='lib_bindings',
    version='1.0.0',
    packages=[],
    author='Ritwik Gupta',
    author_email='x@x.cmu.edu',
    maintainer='Ritwik Gupta',
    maintainer_email='x@x.cmu.edu',
    keywords=['x'],
    classifiers=[],
    description='x',
    ext_modules=[lib_module],
    package_data={
        '': ['PythonBindings.cpp', '*.h', '*.c']
    },
    include_package_data=True
)
```

**Comment by RitwikGupta** [comment]
I understand that `package_data` is the wrong way to go about this, but it does not seem like this functionality exists within colcon itself. I may be wrong here, please correct me!

**Comment by dirk-thomas** [comment]
Please provide a ready-to-run reproducible example.

**Comment by RitwikGupta** [comment]
@dirk-thomas I added a simple example to this repo: https://github.com/RitwikGupta/colcon_cpp_extension_build

**Comment by dirk-thomas** [comment]
The `colcon build` invocation even fails for me for the example when not using `--symlink-install`?

**Comment by dirk-thomas** [comment]
Nvm, ignore my last comment - I had symlink installed enabled in a global config file...

**Comment by dirk-thomas** [comment]
Thank for the example. That will be helpful to test any potential patch.

The normal installation uses this command to achieve an out-of-source build: https://github.com/colcon/colcon-core/blob/a9e1766d9970c441d8c44491d11760a4af1b2daa/colcon_core/task/python/build.py#L64-L78

The `develop` call uses: https://github.com/colcon/colcon-core/blob/a9e1766d9970c441d8c44491d11760a4af1b2daa/colcon_core/task/python/build.py#L89-L96

I am not sure what options need to be passed to `setuptools` to support `develop` out-of-source together with extension modules. Since we don't have that use case at the moment I don't know when I will be able to work on this.

**Comment by RitwikGupta** [comment]
I got it working!

In the `setup()` command in `setup.py`, it is necessary to include a line `data_files = [('.', all_files)]`, where `all_files` is the source and header files necessary for compilation. `colcon build --symlink-install` then works as intended.

The requisite line:
https://github.com/RitwikGupta/colcon_cpp_extension_build/blob/471734c870046c83044c8b90457acf69cc579ca2/src/xlib/setup.py#L44

Getting all files:
https://github.com/RitwikGupta/colcon_cpp_extension_build/blob/471734c870046c83044c8b90457acf69cc579ca2/src/xlib/setup.py#L20-L26

Is there any way to document this? It would be helpful for anyone attempting to build extensions with colcon.

**Comment by dirk-thomas** [comment]
> Is there any way to document this?

`colcon.readthedocs.org` is probably the best place for any documentation. I am not sure where in the existing structure it would fit. Maybe a new item on the existing `user/how-to` page?

**Comment by RitwikGupta** [comment]
Let's close this issue with the merge of the documentation PR over here: https://github.com/colcon/colcon.readthedocs.org/pull/37

Thank you!
