### ISSUE TITLE
Errors sourcing local_setup.sh from zsh

### ISSUE THREAD

**Issue by mjcarroll** [colcon/colcon-core#150]
When building colcon in a bootstrap source workspace, sourcing the `local_setup.sh` generated is unsuccessful in ZSH.

When sourcing, the script doesn't correctly split the list of packages based on newlines as expected.

```
(colcon-venv) ➜  colcon-from-source $ . install/local_setup.sh 
not found: "/home/michael/colcon-venv/colcon-from-source/install/colcon-core
<SNIPPED FOR LENGTH>
colcon-test-result/package.sh"
```

This is caused by `zsh`'s handling of `IFS` and has been previously handled in other shell scripts via the `colcon_zsh_convert_array` function (eg https://github.com/colcon/colcon-core/blob/master/colcon_core/shell/template/package.sh.em#L23)

The expected behavior is that the shell script successfully executes under a `zsh` shell.

**Comment by mjcarroll** [comment]
The current workaround is to initially build the workspace via another shell (`bash`) and then sourcing the generated `local_setup.zsh` or `setup.zsh` file after it is generated.

**Comment by dirk-thomas** [comment]
Another workaround until this is addressed in the generated scripts is to call `setopt SH_WORD_SPLIT` before sourcing the file with `zsh`.

**Comment by hardesh** [comment]
Hey,
I'm still getting this error with Humble when I tried to build and source plotjuggler_ros package. 

Q: Can this error be package specific?
