### ISSUE TITLE
Colcon Build Error

### ISSUE THREAD

**Issue by arijits148** [colcon/colcon-core#153]
While running colcon build in my terminal, I am getting this error. Why and how to resolve it? Kindly help.
![screenshot from 2019-01-14 08-34-21](https://user-images.githubusercontent.com/40036314/51095261-8f3d1d80-17d9-11e9-8076-3897ebb97ce1.png)

**Comment by dirk-thomas** [comment]
Please edit your question and replace the image with text. The content of pictures isn't searchable.

**Comment by dirk-thomas** [comment]
The error message `Duplicate package names not supported` should clearly state what the problem is. You will need to remove the duplicates from your workspace.
