### ISSUE TITLE
update_object method changed in backwards incompatible way.

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-core#156]
Hi Dirk,

I was using this method essentially following your lead on how to do arguments. The latest release broke my package.

https://github.com/colcon/colcon-core/blob/d352c02b88624be589f353f11240bba2cde7034a/colcon_core/verb/__init__.py#L127

I'm seeing:
```
TypeError: update_object() missing 1 required positional argument: 'value_source'
```

Is this considered a public method that I can consume?

Thanks,
Matt

**Comment by dirk-thomas** [comment]
> Is this considered a public method that I can consume?

Yes, it is a public method.

When merging the two functions implemented in the `build` and `test` verb into a new function in the `verb` module I falsely assume that nothing else used those functions. I could have certainly kept the old signature of the function in the verbs to not break potential consumers.

I could either readd the old signature functions (likely marking them deprecated though) or if you are ok with that switch to use the new signature right away. If you point me to the code where it was using the functions I am happy to create a PR for it.

Sorry for not consider this during the refactoring and the inconvenience resulting from it.

**Comment by murphm8** [comment]
Thanks for the quick reply. We have published a new version of colcon-bundle that supports the new method signature.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket then.
