### ISSUE TITLE
Documentation unclear on how to build with no more than one thread/job

### ISSUE THREAD

**Issue by knicko** [colcon/colcon-core#164]
The documentation on https://colcon.readthedocs.io/en/released/migration/ament_tools.html is unclear on how to specify the number of build jobs, which has been possible with ament. Using four or more build jobs prevents building large codebases like ROS 2 on low-memory hardware with colcon. Though there is a sequential option, the package processed is still built with multiple jobs when invoking `colcon build --executor sequential`. It would be most helpful, if the linked documentation page would comment on the availability of specifying the number of build jobs, and if available, how to.

**Comment by dirk-thomas** [comment]
Please see colcon/colcon.readthedocs.org#43 which describes how former `--make-flags` can be mapped. Please comment if that clarifies / answers your question.

**Comment by knicko** [comment]
The question is answered, thank you very much!
