### ISSUE TITLE
--event-handlers args: inconsistency between code and doc

### ISSUE THREAD

**Issue by rhaschke** [colcon/colcon-core#176]
While `colcon build --help suggest`, that `--event-handlers` accepts both `+` and `-` versions of all names:
```
Event handler arguments:
  --event-handlers [name1+ [name2- ...]]
                        Enable (+) or disable (-) event handlers
```

colcon actually complains when passing `console_stderr+`:
`colcon build: error: argument --event-handlers: invalid choice: 'console_stderr+' (choose from 'console_cohesion+', 'console_direct+', 'console_package_list+', 'console_start_end-', 'console_stderr-', 'desktop_notification-', 'event_log-', 'log-', 'log_command-', 'status-', 'store_result-', 'summary-', 'terminal_title-')`

I suggest to indeed accept both +/- versions to allow for explicit statement of desired output mode.

**Comment by dirk-thomas** [comment]
I agree that I would be better to accept both versions of all names. Currently only the options not also set are listed as choices to make the completion not helpful. I would be good to preserve that

**Comment by dirk-thomas** [comment]
Please see/try #178 for the proposed change.
