### ISSUE TITLE
Remove explicit quoting of --*cmake-args arguments

### ISSUE THREAD

**Issue by rhaschke** [colcon/colcon-core#177]
As stated in #18, colcon requires arguments passed to `--*cmake-args` to be quoted.
This is rather unnatural. I suggest to follow the standard, also used in catkin_tools any many other cmdline tools, and consume all arguments after `--*cmake-args` for this list. A final `--` indicates the end of the list.

**Comment by sloretz** [comment]
I think this was fixed (by #63?). I don't quote cmake args anymore, and instead of a terminating `--` any argument colcon understands terminates it.

Example:
```
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug --packages-select rclpy
```

**Comment by rhaschke** [comment]
Thanks for this hint. Works as described.
However, it is non-standard (and ambiguous) that the `--` end indicator is _not_ supported / required.

**Comment by dirk-thomas** [comment]
> However, it is non-standard (and ambiguous) that the `--` end indicator is not supported / required.

`--` is used to indicate that the following parameters are positional arguments. Can you please describe which exact commands you expect to work / not work?

**Comment by rhaschke** [comment]
Coming from catkin_tools, which also supports an argument `--cmake-args`, I naively used the following command:
`colcon build --catkin-cmake-args ... -- --ament-cmake-args ... -- --event-handlers status-
`
which colcon didn't accepted:
```
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
              {build,extension-points,extensions,info,list,metadata,test,test-result,version-check}
              ...
colcon: error: unrecognized arguments: -- --ament-cmake-args -- --event-handlers status-
```
If there would be an option that you would like to pass as a cmake-args argument, that is also simultaneously an accepted colcon option, this wouldn't be possible right now if I understand your approach correctly.

As info, catkin_tools' docs read as follows:

      --cmake-args ARG [ARG ...]
                        Arbitrary arguments which are passes to CMake. It
                        collects all of following arguments until a "--" is read.

**Comment by dirk-thomas** [comment]
> I naively used the following command:
`colcon build --catkin-cmake-args ... -- --ament-cmake-args ... -- --event-handlers status-` 
which `colcon` didn't accepted:

There is no need for the `--` in this example. `argparse` out of the box is able to handle this case just fine.

> ... this wouldn't be possible right now if I understand your approach correctly.

It is less "my" approach than what is implemented in `argparse`. In contrast to `catkin_tools` there is no custom argument processing involved.

> If there would be an option that you would like to pass as a cmake-args argument, that is also simultaneously an accepted colcon option, this wouldn't be possible right now

That is correct for `argparse`. The recommended workaround for this for arguments using `nargs='*'` is to also pass `type=str.lstrip` which will ensure that spaces from each parameter are stripped. That allows you to pass `--cmake-args " --arg-to-pass-to-CMake-even-if-it-is-also-a-colcon-arg"`.

**Comment by rhaschke** [comment]
Ok. So this is a shortcoming of argparse already. Closing this as it is practically not so important (we don't have an overlap between colcon and cmake args).
