### ISSUE TITLE
don't create build/install/log folder if no packages were found

### ISSUE THREAD

**Issue by Karsten1987** [colcon/colcon-core#182]
It happened a couple of times now that I invoke `colcon build --packages-select <package_name>` in the wrong directory. Obviously, the package in question is not being found and thus no compilation is triggered. However, what's a bit annoying is that the `build`, `install` and `log` folders are created which I then have to remove manually.

I know this is wrong user behavior, but I believe it makes sense to check whether at least one package can be compiled before creating these folders.

**Comment by dirk-thomas** [comment]
I am not sure these directories should be deleted automatically in that case.

E.g. the `log` directory still contains potentially valuable information about what happened during the invocation, what paths were considered, what packages were found / ignored / selected. And the `install` directory still contains a sourcable workspace after that (I assume).

So I don't see how the these directories can be deleted automatically in the described case.

**Comment by tfoote** [comment]
They probably can't be deleted automatically as you don't know if they were preexisting. But their creation could be deferred until there is contents to write into them or at least until after the package count is checked.

**Comment by dirk-thomas** [comment]
> But their creation could be deferred until there is contents to write into them or at least until after the package count is checked.

That is certainly not the case for the `log` directory since logging starts long before that check.

**Comment by dirk-thomas** [comment]
@Karsten1987 can you clarify the status of this ticket? If there is anything we can do it is not obvious to me atm what that should be.

**Comment by Karsten1987** [comment]
I'll close this ticket as I understood the consensus was to not remove the creation of the `log` folder. I guess it could still be nice to not create a `build` and `install`, but essentially doesn't really matter.
