### ISSUE TITLE
Logging code crashes with KeyError

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#186]
see colcon_core/package_identification/python.py
`"Ignoring unknown symbol '{symbol}' in '{requirement}'".format(locals()))`

Please create a separate PR for this unrelated change.

_Originally posted by @dirk-thomas in https://github.com/colcon/colcon-core/pull/184_

**Comment by dirk-thomas** [comment]
Can you please create a PR for the previously suggested change: https://github.com/colcon/colcon-core/pull/184#discussion_r279201215

**Comment by dirk-thomas** [comment]
Addressed in #190.
