### ISSUE TITLE
'BuildPackageArguments' object has no attribute 'name'

### ISSUE THREAD

**Issue by mangoSteve** [colcon/colcon-core#189]
Hello there,

I am trying to install Autoware on my Jetson Xavier device(Ubuntu 18.04 on ARMv8, 64-bit). I installed ROS melodic and followed https://github.com/autowarefoundation...

I cloned feature/melodic branch and tried to follow the steps.

Everything went fine except that gksu cannot be installed as it is abandoned by Ubuntu 18

But when I run ./colcon_release:

	nvidia@jetson-0423218010999:~/Documents/autoware/ros$ ./colcon_release 
	Starting >>> autoware_build_flags
	Starting >>> autoware_msgs
	Starting >>> autoware_config_msgs
	Starting >>> tablet_socket_msgs
	Finished <<< autoware_build_flags [15.1s]                                      
	Starting >>> vector_map_msgs
	[Processing: autoware_config_msgs, autoware_msgs, tablet_socket_msgs, vector_map_msgs]
	Finished <<< tablet_socket_msgs [46.4s]                                  
	Starting >>> autoware_system_msgs
	[Processing: autoware_config_msgs, autoware_msgs, autoware_system_msgs, vector_map_msgs]
	Finished <<< autoware_config_msgs [1min 31s] 
	Starting >>> autoware_can_msgs               
	Finished <<< autoware_system_msgs [49.4s]    
	Starting >>> autoware_health_checker
	--- stderr: autoware_health_checker          
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
	    rc = await self.task(*args, **kwargs)
	  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 92, in __call__
	    return await task_method(*args, **kwargs)
	  File "/usr/lib/python3/dist-packages/colcon_ros/task/catkin/build.py", line 71, in build
	    skip_hook_creation=True, additional_targets=additional_targets)
	  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 97, in build
	    .format_map(locals())
	AttributeError: 'BuildPackageArguments' object has no attribute 'name'---

	Failed   <<< autoware_health_checker    [ Exited with code 1 ]
	Aborted  <<< autoware_can_msgs                          
	Aborted  <<< autoware_msgs                              
	Aborted  <<< vector_map_msgs                

	Summary: 4 packages finished [3min 30s]
	  1 package failed: autoware_health_checker
	  3 packages aborted: autoware_can_msgs autoware_msgs vector_map_msgs
	  1 package had stderr output: autoware_health_checker
	  130 packages not processed
	'BuildPackageArguments' object has no attribute 'name'

**Comment by dirk-thomas** [comment]
The line in which the exception happens is supposed to output a warning. Please try the patch from colcon/colcon-cmake#43 to resolve the exception.

Even after that you should still see a warning:

> Could not build CMake package 'autoware_health_checker' because the CMake cache has no 'CMAKE_PROJECT_NAME' variable

Can you please share the content of the file `build/autoware_health_checker/CMakeCache.txt`?

**Comment by mangoSteve** [comment]
Yes with pleasure,

But it seems that there is no such file
`
nvidia@jetson-0423218010999:~/Documents/autoware/ros/build/autoware_health_checker$ ls
cmake_args.last  colcon_build.rc  colcon_command_prefix_build.sh  colcon_command_prefix_build.sh.env
`

**Comment by dirk-thomas** [comment]
> But it seems that there is no such file

Is that before or after another build invocation? What is the output of the new build?

**Comment by mangoSteve** [comment]
Well, unluckily, it seems to be an unsuccessful build. In fact, the build failed later as another module `waypoint_follower` cannot find files that should be generated during the building of this module `autoware_health_checker`


nvidia@jetson-0423218010999:~/Documents/autoware/ros$ ./colcon_release 
Starting >>> autoware_build_flags
Starting >>> autoware_msgs
Starting >>> autoware_config_msgs
Starting >>> tablet_socket_msgs
Finished <<< autoware_build_flags [23.2s]                                                   
Starting >>> vector_map_msgs
[Processing: autoware_config_msgs, autoware_msgs, tablet_socket_msgs, vector_map_msgs]
Finished <<< tablet_socket_msgs [1min 12s]                                         
Starting >>> autoware_system_msgs
[Processing: autoware_config_msgs, autoware_msgs, autoware_system_msgs, vector_map_msgs]
[Processing: autoware_config_msgs, autoware_msgs, autoware_system_msgs, vector_map_msgs]
Finished <<< autoware_system_msgs [1min 6s]                                         
Starting >>> autoware_health_checker                                                
[168.705s] WARNING:colcon.colcon_cmake.task.cmake.build:Could not build CMake package 'autoware_health_checker' because the CMake cache has no 'CMAKE_PROJECT_NAME' variable
Finished <<< autoware_health_checker [22.6s]                                        
Starting >>> autoware_can_msgs
[Processing: autoware_can_msgs, autoware_config_msgs, autoware_msgs, vector_map_msgs]
Finished <<< autoware_config_msgs [3min 21s]                                        
Starting >>> gnss
Finished <<< autoware_can_msgs [54.8s]                                              
Starting >>> rslidar_msgs
Finished <<< gnss [27.9s]                                                           
Starting >>> sick_ldmrs_description
Finished <<< sick_ldmrs_description [24.0s]                                         
Starting >>> sick_ldmrs_msgs
Finished <<< rslidar_msgs [43.5s]                                                   
Starting >>> rslidar_driver
Finished <<< sick_ldmrs_msgs [35.7s]                                                           
Starting >>> sick_ldmrs_driver
Finished <<< autoware_msgs [4min 59s]                                                  
Starting >>> waypoint_follower
--- stderr: waypoint_follower                                                          
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "autoware_health_checker" with any of the following names:

    autoware_health_checkerConfig.cmake
    autoware_health_checker-config.cmake

  Add the installation prefix of "autoware_health_checker" to
  CMAKE_PREFIX_PATH or set "autoware_health_checker_DIR" to a directory
  containing one of the above files.  If "autoware_health_checker" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:12 (find_package)


---
Failed   <<< waypoint_follower	[ Exited with code 1 ]
Aborted  <<< vector_map_msgs                                                                       
Aborted  <<< rslidar_driver                                                                       
--- stderr: sick_ldmrs_driver                                                          
make[2]: *** [CMakeFiles/sick_ldmrs_node.dir/src/sick_ldmrs_node.cpp.o] Interrupt
make[1]: *** [CMakeFiles/sick_ldmrs_node.dir/all] Interrupt
make: *** [all] Interrupt
---
Aborted  <<< sick_ldmrs_driver
                                          
Summary: 11 packages finished [11min 12s]
  1 package failed: waypoint_follower
  3 packages aborted: rslidar_driver sick_ldmrs_driver vector_map_msgs
  2 packages had stderr output: sick_ldmrs_driver waypoint_follower
  123 packages not processed

**Comment by dirk-thomas** [comment]
As mentioned before the fix to the warning message won't resolve the fact that the warning is happening.

The new CMake error is due to CMake not being able to find the `autoware_health_checker` package. That is a direct consequence of the warning you see for the `autoware_health_checker` package:

> WARNING:colcon.colcon_cmake.task.cmake.build:Could not build CMake package 'autoware_health_checker' because the CMake cache has no 'CMAKE_PROJECT_NAME' variable

To debug this problem I would suggest to ask on the upstream package since I could only provide general debugging suggestions here (e.g. delete `build/autoware_health_checker` and try again `colcon_release --packages-select autoware_health_checker`).

**Comment by mangoSteve** [comment]
Thanks a lot. I cloned again and rebuilt it, and that works.

**Comment by jjully** [comment]
What did you clone again? Actually im suffering from same error, but cannot find the way
I set CMAKE_PREFIX_PATH to dir which has those cmake files but still don't work
