### ISSUE TITLE
verbose makefile argument via cmake not working as expected

### ISSUE THREAD

**Issue by PeterMitrano** [colcon/colcon-core#192]
I would expect the following command to print verbose makefile output, as if I invoked `make VERBOSE=1`, but instead it does not print anything besides the normal colcon output.

    colcon build --cmake-args -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON --packages-select Gazebo

Apologies if this is the wrong colcon repo!

**Comment by dirk-thomas** [comment]
If you have `colcon-output` installed by default you won't see any `stdout` output of the build process. Only `stderr` output is printed by default.

Have you looked in the log file (`log/latest_build/Gazebo/stdout.log`) if it contains the information you are expecting?

As an alternative you can change the output by passing e.g. `--event-handlers console_cohesion+` (or in the case you are building only a single package even stream the output when it comes in: `--event-handlers console_cohesion+`).

**Comment by PeterMitrano** [comment]
Yep, that's what I was looking for. Thanks!
