### ISSUE TITLE
Difference between `setup.sh/bash/zsh` and `local_setup.sh/bash/zsh` 

### ISSUE THREAD

**Issue by murphm8** [colcon/colcon-core#204]
Could you explain the different use cases for sourcing `setup.sh/bash/zsh` vs `local_setup.sh/bash/zsh`?

It looks like the [docs](https://colcon.readthedocs.io/en/released/user/quick-start.html) are using `local_setup.bash` now?

**Comment by dirk-thomas** [comment]
The `local_setup` files set the environment for the current workspace. It doesn't consider other parent workspaces. If there are any you need to source them manually using their files.

The `setup` files set the environment for all the parent workspaces first (by sourcing their `local_setup` files in the order they appear in `COLCON_PREFIX_PATH` when this workspace was built) and then sources the `local_setup` file of this workspace.
