### ISSUE TITLE
colcon buffers verbose output

### ISSUE THREAD

**Issue by nickolai-voyage** [colcon/colcon-core#206]
When building with
`colcon build --event-handlers=console_cohesion+ --cmake-args -DCMAKE_VERBOSE_MAKEFILE=ON`

The output of cmake is buffered until colcon finishes. Could this be changed so that output is immediate?

**Comment by dirk-thomas** [comment]
If you want unbuffered output (which implies interleaved output when building packages in parallel) you can use the option `--event-handlers console_direct+` instead.

See `colcon build --help` as well as the [docs](https://colcon.readthedocs.io/en/released/user/how-to.html#show-all-output-immediately-on-the-console).
