### ISSUE TITLE
Colcon processes CMakeLists files it shouldn't (?)

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#210]
It seems that colcon recurses from base-paths until it finds a CMakeLists.txt file, even if there is no package.xml.

This runs counter to my naive expectation that Colcon will only build a CMakeLists files only if specified by a package.xml file with build type `cmake` or `ament_cmake`.

E.g.
```
$ ls -1
build
CMakeLists.txt
install
log
src

$ ls -1 src
ament_cmake
ament_lint
angles
...

$ colcon build
Starting >>> ros2_ws 
[0.859s] WARNING:colcon.colcon_cmake.task.cmake.build:Could not run installation step for package 'ros2_ws' because it has no 'install' target
Finished <<< ros2_ws [0.15s]

Summary: 1 package finished [0.79s]
```

**Comment by dirk-thomas** [comment]
`colcon` is designed to be not specific to ROS. As such it is also able to process packages which do not have a `package.xml` file.

Pure CMake packages are for example identified by the presence of a `CMakeLists.txt` file. A common example is [Fast-RTPS](https://github.com/eProsima/Fast-RTPS) which is being built as part of ROS 2 but doesn't have a ROS manifest file.

You can run `colcon info` (with similar arguments than `colcon build`) to see what packages are being found and with which type they are being processed.
