### ISSUE TITLE
Question | How to attach a python debugger when developing colcon

### ISSUE THREAD

**Issue by ruffsl** [colcon/colcon-core#217]
I'd like work on extending `colcon_package_selection` package, but I can't figure out how to attach a python debugger to the breakpoint I'd like to inspect when working inside a colcon workspace in itself. So far I've bootstrapped a workspace as per:
https://colcon.readthedocs.io/en/released/developer/bootstrap.html

Then I open `colcon-from-source/src/colcon_package_selection` in VS Code with the python extension installed from the same terminal with the venv activated and install/local_setup.bash sourced, so that vscode pickup on the venv environment. Following this guid I set up the `.vscode/launch.json` for setting the debugger:
https://code.visualstudio.com/docs/python/debugging

``` yaml
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: colcon dev",
            "type": "python",
            "request": "launch",
            "cwd": "~/ws/navigation2/overlay_ws",
            "program": "${workspaceFolder}/../colcon-core/bin/colcon",
            "args": [
                "list",
                "--packages-select-build-failed"
            ],
        },
    ]
}
```

However, I can't get the rest of the extensions to load, like list for example:

```
$ cd ~/ws/navigation2/overlay_ws ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /home/ubuntu/ws/colcon-venv/bin/python /home/ubuntu/.vscode/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py --default --client --host localhost --port 35017 /home/ubuntu/ws/colcon-from-source/src/colcon-package-selection/../colcon-core/bin/colcon list --packages-select-build-failed 
usage: /home/ubuntu/ws/colcon-from-source/src/colcon-package-selection/../colcon-core/bin/colcon
       [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL] {build,test} ...
/home/ubuntu/ws/colcon-from-source/src/colcon-package-selection/../colcon-core/bin/colcon: error: argument verb_name: invalid choice: 'list' (choose from 'build', 'test')
```

I tried changing the python executable to ensure that the workspace is sourced for ptvsd_launcher.py: 

``` diff
            "name": "Python: colcon dev",
+            "linux": {
+                "pythonPath": "/home/ubuntu/ws/colcon-from-source/ws_python"
+            },
``` 

``` bash
#!/bin/bash
# ws_python

source ~/ws/colcon-venv/bin/activate
source ~/ws/colcon-from-source/install/local_setup.bash
python "$@"
```

But that didn't fix anything. If I try `--symlink-install`ing and point to the install folder instead:

``` diff
            "name": "Python: colcon dev",
-            "program": "${workspaceFolder}/../colcon-core/bin/colcon",
+            "program": "${workspaceFolder}/../../install/colcon-core/bin/colcon",
``` 

Then I still have some issues with the `load_entry_point` after list command prints to stdout:
```
Exception has occurred: SystemExit
  File "/home/ubuntu/ws/colcon-from-source/install/colcon-core/bin/colcon", line 11, in <module>
    load_entry_point('colcon-core', 'console_scripts', 'colcon')()
```

**Comment by dirk-thomas** [comment]
> However, I can't get the rest of the extensions to load

If you only invoke the bootstrap script of `colcon` (`colcon-core/bin/colcon`) you will only get the extensions which are part of `colcon-core`.

After you have bootstrapped your colcon workspace you should source the environment as mentioned in the instructions:

> `. install/local_setup.bash`

And from then on you should invoke the `colcon` executable which is on your `PATH` instead of the bootstrap script above.

If you want to invoke this in your development environment you have to make sure it has the same environment setup as after sourcing the setup file (either by manually configuring it or by opening your editor / IDE in a terminal which has the environment already setup.

**Comment by ruffsl** [comment]
Ok, so I got the debugger working by tweaking the `.vscode/launch.json` so the script to setup the environment is correctly used as the interpreter for running `ptvsd_launcher.py` via `pythonPath`:

``` diff
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Python: colcon2",
+            "linux": {
+                "pythonPath": "${workspaceFolder}/../../ws_python"
+            },
            "type": "python",
            "request": "launch",
            "cwd": "/home/ubuntu/ws/navigation2/overlay_ws",
            "program": "${workspaceFolder}/../../install/colcon-core/bin/colcon",
            "args": [
                "list",
                "--packages-select-build-failed",
            ],
        },
    ]
}
```

``` bash
#!/bin/bash
# ws_python

source ~/ws/colcon-venv/bin/activate
source ~/ws/colcon-from-source/install/local_setup.bash
python "$@"
```

The debugger now expands to running this in new console:

``` bash
$ /home/ubuntu/ws/colcon-from-source/src/colcon-package-selection/../../ws_python \
/home/ubuntu/.vscode-server/extensions/ms-python.python-2019.8.30787/pythonFiles/ptvsd_launcher.py \
  --default --client --host localhost --port 43859 \
  /home/ubuntu/ws/colcon-from-source/src/colcon-package-selection/../../install/colcon-core/bin/colcon \
    list \
      --packages-select-build-failed 
```

**Comment by Ryanf55** [comment]
Hey there, this is great info. Is there any way this could be folded into some documentation?
