### ISSUE TITLE
Colcon generating stderr on successful python tests

### ISSUE THREAD

**Issue by stonier** [colcon/colcon-core#231]
**Details**

* Ubuntu: Bionic (18.04)
* ROS Distro: dashing
* Example package: https://github.com/stonier/foo
* Colcon Deb: python-colcon-core 0.4.0-1
* PyTest Deb (system deb): python3-pytest 3.3.2-2

**What**

* `colcon test` seems to be generating spurious results on stderr which is failing tests even if the tests should legitimately pass
* `colcon test` is doing something different to `python3 setup.py test` (reporting back with test 'ok' rather than 'Success')

**Expected**

* No spurious collections of stderrr and subsequent failure
* Results of `colcon test` and `python3 setup.py test` do not differ?

**Example** 

Execution and output (colcon test)

```
colcon test --packages-select foo --event-handlers console_direct+ --build-base build --install-base install --test-result-base test_results --executor sequential
Starting >>> foo     
running test                      
running egg_info
writing /mnt/mervin/workspaces/dashing/py_trees/build/foo/foo.egg-info/PKG-INFO
writing dependency_links to /mnt/mervin/workspaces/dashing/py_trees/build/foo/foo.egg-info/dependency_links.txt
writing top-level names to /mnt/mervin/workspaces/dashing/py_trees/build/foo/foo.egg-info/top_level.txt
reading manifest file '/mnt/mervin/workspaces/dashing/py_trees/build/foo/foo.egg-info/SOURCES.txt'
writing manifest file '/mnt/mervin/workspaces/dashing/py_trees/build/foo/foo.egg-info/SOURCES.txt'
running build_ext
ROS INIT                          
Success
ROS Shutdown
test_success (tests.test_foo.TestActionServers) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
--- stderr: foo
test_success (tests.test_foo.TestActionServers) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
---
Finished <<< foo [0.58s]

Summary: 1 package finished [0.70s]
  1 package had stderr output: foo
colcon test-result --all
Summary: 0 tests, 0 errors, 0 failures, 0 skipped
```

Execution and output (`python3 setup.py test`)

```
python3 setup.py test
running test
running egg_info
creating foo.egg-info
writing foo.egg-info/PKG-INFO
writing dependency_links to foo.egg-info/dependency_links.txt
writing top-level names to foo.egg-info/top_level.txt
writing manifest file 'foo.egg-info/SOURCES.txt'
reading manifest file 'foo.egg-info/SOURCES.txt'
writing manifest file 'foo.egg-info/SOURCES.txt'
running build_ext
ROS INIT
test_success (tests.test_foo.TestActionServers) ... Success
ok
ROS Shutdown

----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
```

**Comment by stonier** [comment]
Actually, perhaps not failing anything - `colcon test` has return value 0, just generating spurious stderr.

**Comment by dirk-thomas** [comment]
> `colcon test` seems to be generating spurious results on stderr which is failing tests even if the tests should legitimately pass

What you are seeing (the `stderr` output) is the default behavior of `python3 setup.py test` afaik. If you run the same command manually you will notice that it does output to `stderr`. `colcon` is just forwarding that output.

> `colcon test` is doing something different to `python3 setup.py test` (reporting back with test 'ok' rather than 'Success')

`colcon` has to capture the output. That already changes the behavior of the test output. You can try that by calling the command `python3 setup.py test` once as is and another time while piping the result somewhere, e.g. ` | less`.

> PyTest Deb (system deb): python3-pytest 3.3.2-2

While you have `pytest` installed your package doesn't use it for running its tests. To run your tests using `pytest` you have to add `tests_require=['pytest']` to your setup arguments. That way you should not get any output on `stderr` and get all the benefits `pytest` has to offer (e.g. debug information for failed asserts).

> Summary: 0 tests, 0 errors, 0 failures, 0 skipped

Vanilla unit tests in Python don't generate any result file `colcon` can pick up. When you switch to `pytest` it should generate the results in `build/foo/pytest.xml`.

**Comment by stonier** [comment]
Oh wow...

```
test_success (tests.test_foo.TestActionServers) ... Success
ok
```
The `Success` is on `stdout`, while the rest is on `stderr`. Completely bamboozled me and subsequently had me chasing red herrings. Still odd that it reports out on stderr.

Thanks for the great explanation - I'll switch back to nosetest with its reports / or pytest directly as you mentioned above.

**Comment by dirk-thomas** [comment]
> I'll switch back to nosetest with its reports / or pytest directly as you mentioned above.

I would highly recommend using `pytest`. Imo it is way superior in terms of features as well as more actively maintained.
