### ISSUE TITLE
Colcon shell.get_environment_variables does not correctly handle some Windows environment variables

### ISSUE THREAD

**Issue by KazNX** [colcon/colcon-core#248]
When colcon_core.shell.get_environment_variables() is decoding the environment variable string, it makes invalid assumptions about the format of a valid environment variable key. Specifically, it uses the regular expression: '^[a-zA-Z0-9_%]+$' (around line 328). This does not correctly handle the environment variable strings `PROGRAMFILES(X86)` (cmd) or `ProgramFiles(x86)` (PowerShell). Instead, this environment variable and its key are appented to the previous environment variable, pontetially invalidating that variable.

This can result in a polluted environment causing downstream issues. See https://github.com/colcon/colcon-cmake/issues/54

The expected behaviour is that `PROGRAMFILES(X86)` is stored as its own key/value pair in the resulting environment dictionary and other valid variables are not polluted.

One potential fix is to use a different regular expression for Windows, allowing '(' and ')' characters.

**Comment by dirk-thomas** [comment]
Can you please include steps of a concrete problem to reproduce.

**Comment by KazNX** [comment]
Here's what I have to highlight the issue:

- Extract the attached file
- Run a Visual Studio command prompt. I used Visual Studio 2019 x64 native.
- Change into the directory where the file has been extracted
- Confirm the presence of the environment variable `PROGRAMFILES(X86)` via `echo %PROGRAMFILES(X86)%`. The value should be `C:\Program Files (x86)`
- Modify the colcon shell source as indicated below.
- Run colcon build
- Observe the output will contain the text `combine 'ProgramFiles(x86)=C:\Program Files (x86)' into '<previous-key>' where <previous-key> is the previous entry in the environment table being built.

Expected behaviour: The line "combine ..." should not be printed for `ProgramFiles(x86)`.

Note: depending on the order in which the variables come in, you may also reproduce https://github.com/colcon/colcon-cmake/issues/54

The code modifications to show this issue are made to `colcon_core\shell\__init__.py` in the function `get_environment_variables()`. In the else block at the end of the `for` loop, I've changed the branch to:
```
            # assume a line without an equal sign or with a "key" which is not
            # a valid name is a continuation of the previous line
            if env:
                env[list(env.keys())[-1]] += '\n' + line
                print("combine '" + line + "' into '" + list(env.keys())[-1] + "'")
```

Full source for the function is below. This also contains a simple (though technically incorrect) fix to the regular expression, though it has been commented out.:

```
async def get_environment_variables(cmd, *, cwd=None, shell=True):
    """
    Get the environment variables from the output of the command.

    :param args: the sequence of program arguments
    :param cwd: the working directory for the subprocess
    :param shell: whether to use the shell as the program to execute
    :rtype: dict
    """
    output = await check_output(cmd, cwd=cwd, shell=shell)
    env = OrderedDict()
    for line in output.splitlines():
        line = line.rstrip()
        if not line:
            continue
        encoding = locale.getpreferredencoding()
        try:
            line = line.decode(encoding)
        except UnicodeDecodeError:
            line_replaced = line.decode(encoding=encoding, errors='replace')
            logger.warning(
                'Failed to decode line from the environment using the '
                "encoding '{encoding}': {line_replaced}".format_map(locals()))
            continue
        parts = line.split('=', 1)
        if len(parts) == 2 and re.match('^[a-zA-Z0-9_\(\)%]+$', parts[0]):
        # if len(parts) == 2 and re.match('^[a-zA-Z0-9_%]+$', parts[0]):
            # add new environment variable
            env[parts[0]] = parts[1]
        else:
            # assume a line without an equal sign or with a "key" which is not
            # a valid name is a continuation of the previous line
            if env:
                env[list(env.keys())[-1]] += '\n' + line
                print("combine '" + line + "' into '" + list(env.keys())[-1] + "'")
    assert len(env) > 0, "The environment shouldn't be empty"
    return env
```

[helloworld.zip](https://github.com/colcon/colcon-core/files/3742816/helloworld.zip)

**Comment by dirk-thomas** [comment]
Thanks for the context and example. Can you please try the proposed patch in #249 and comment if that resolves the problem for you.

**Comment by KazNX** [comment]
The patch seems ok. It handled the injection, so I'll watch for the sporradic failures.
