### ISSUE TITLE
colcon packages on ROS 2 repos outdated for Eoan

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#253]
I'm using Ubuntu Eoan and the last version of colcon on the ROS 2 repositories for that platform is `0.3.23`.
Is it possible to release the newer versions in Eoan ?

Thanks!

**Comment by dirk-thomas** [comment]
Eoan is currently not listed as a supported suite and there should be no Debian packages for it in the first place: https://github.com/colcon/colcon-core/blob/f8b78a152280c91152d30341db837e50b03391d5/stdeb.cfg#L4

I guess a set of packages was imported once manually by @nuclearsandwich and the decision if we want to provide debs for non-LTS distros is pending on #212.

**Comment by mikaelarguedas** [comment]
Thanks for the pointer

Closing this then
