### ISSUE TITLE
Exception in shell extension 'bat'

### ISSUE THREAD

**Issue by dhood** [colcon/colcon-core#26]
Opening here with hopes someone is aware of something that has changed recently.

Trying to figure out what has caused my CI to fail with a colcon error: https://ci.ros2.org/job/ci_windows/4366/console

I'm only testing changes to the rmw_opensplice repo so I suspect this would fail on master currently too.
```
Starting >>> rosidl_typesupport_connext_cpp
00:08:47.464 colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['C:\\J\\workspace\\ci_windows\\ws\\build\\rosidl_typesupport_connext_cpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
00:08:47.465 Traceback (most recent call last):
00:08:47.465   File "C:\Python36\lib\site-packages\colcon_core\shell\__init__.py", line 208, in get_command_environment
00:08:47.465     task_name, Path(build_base), dependencies)
00:08:47.465   File "C:\Python36\lib\site-packages\colcon_core\shell\bat.py", line 97, in generate_command_environment
00:08:47.465     env = await get_environment_variables(cmd, cwd=str(build_base))
00:08:47.465   File "C:\Python36\lib\site-packages\colcon_core\shell\__init__.py", line 244, in get_environment_variables
00:08:47.465     output = await check_output(cmd, cwd=cwd, shell=shell)
00:08:47.465   File "C:\Python36\lib\site-packages\colcon_core\subprocess.py", line 108, in check_output
00:08:47.466     assert not rc, 'Expected {args} to pass'.format_map(locals())
00:08:47.466 AssertionError: Expected ['C:\\J\\workspace\\ci_windows\\ws\\build\\rosidl_typesupport_connext_cpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
00:08:47.466 
00:08:47.468 colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
00:08:47.476 Failed   <<< rosidl_typesupport_connext_cpp	 [ Exited with code 1 ]
```

**Comment by dhood** [comment]
It's still happening even after a rebase but it doesn't happen on the changes to the `rmw_opensplice` repo, so there must just be something a bit "off" in the `rmw_connext` changes. I plan to refactor the changes in https://github.com/ros2/rmw_connext/pull/274/files anyway to match the opensplice changes, so I'm going to close this because with any luck that will resolve this issue.

**Comment by dirk-thomas** [comment]
Maybe to later but it would be good to try running the file the error message complained about (`C:\\J\\workspace\\ci_windows\\ws\\build\\rosidl_typesupport_connext_cpp\\colcon_command_prefix_build.bat`). Maybe that shows any information why the script failed.
