### ISSUE TITLE
Python packages built with --symlink-install does not respect packages_dir

### ISSUE THREAD

**Issue by sloretz** [colcon/colcon-core#272]
Follow up from #271

[`package_dir={'foo': 'lib'}` means `lib/__init__.py` is installed as `foo/__init__.py`](https://docs.python.org/3.8/distutils/setupscript.html#listing-whole-packages), however that currently doesn't work when using `--symlink-install`. This is pretty much the same as  pypa/setuptools#230 which says `python setup.py develop` doesn't do the right thing either. However, since `colcon-core` isn't using the `.pth` normally created by `setup.py develop` it does seem fair to call it a difference between `colcon build` and `colcon build --symlink-install`.

To reproduce

```console
sloretz@nxt:~/ws/misc-py/src$ tree bob
bob
├── lib
│   └── __init__.py
└── setup.py

1 directory, 2 files
sloretz@nxt:~/ws/misc-py/src$ cat bob/lib/__init__.py 
print('hello bob')
sloretz@nxt:~/ws/misc-py/src$ cat bob/setup.py 
from setuptools import setup

setup(
    name='bob',
    version='0.1.0',
    packages=['bob'],
    package_dir={'bob': 'lib'},
    install_requires=['setuptools'],
)
```

Run `colcon build` and in python `import bob`. It works as expected.

```
sloretz@nxt:~/ws/misc-py$ . install/setup.bash 
sloretz@nxt:~/ws/misc-py$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bob
hello bob
```

Then run clean the workspace, run `colcon build --symlink-install` and try importing `bob`, it doesn't work, but importing `lib` does.

```
sloretz@nxt:~/ws/misc-py$ . install/setup.bash 
sloretz@nxt:~/ws/misc-py$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bob
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bob'
>>> import lib
hello bob
```

**Comment by dirk-thomas** [comment]
> `package_dir={'foo': 'lib'}`

Do you have a real world package which uses this or this just an example?

**Comment by sloretz** [comment]
This is just an example. I don't know of a package that uses `package_dir` like this outside of examples from distutils' documentation
