### ISSUE TITLE
"call ros2_master\install\local_setup.bat" fails with error message "AssertionError: Unknown environment hook type: set"

### ISSUE THREAD

**Issue by Sleazey** [colcon/colcon-core#289]
Occurrence on Windows 10:

C:\dev>call ros2_master\install\local_setup.bat
Traceback (most recent call last):
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 295, in
main()
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 49, in main
args.additional_extension
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 179, in get_commands
package_dsv_path, prefix, primary_extension, additional_extension)
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 224, in process_dsv_file
additional_extension=additional_extension)
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 224, in process_dsv_file
additional_extension=additional_extension)
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 199, in process_dsv_file
type_, remainder, prefix)
File "C:\dev\ros2_master\install_local_setup_util_bat.py", line 264, in handle_dsv_types_except_source
assert False, 'Unknown environment hook type: ' + type_
AssertionError: Unknown environment hook type: set

C:\dev>colcon version-check
colcon-cmake 0.2.17: up-to-date
colcon-core 0.4.5: up-to-date
colcon-defaults 0.2.2: up-to-date
colcon-devtools 0.2.2: up-to-date
colcon-library-path 0.2.1: up-to-date
colcon-metadata 0.2.2: up-to-date
colcon-notification 0.2.11: up-to-date
colcon-output 0.2.7: up-to-date
colcon-package-information 0.3.0: up-to-date
colcon-package-selection 0.2.5: up-to-date
colcon-parallel-executor 0.2.4: up-to-date
colcon-pkg-config 0.1.0: up-to-date
colcon-powershell 0.3.6: up-to-date
colcon-python-setup-py 0.2.2: up-to-date
colcon-recursive-crawl 0.2.0: up-to-date
colcon-ros 0.3.14: up-to-date
colcon-test-result 0.3.8: up-to-date

C:\dev>python --version
Python 3.7.5

**Comment by dirk-thomas** [comment]
The stacktrace looks weird. The path `C:\dev\ros2_master\install_local_setup_util_bat.py` doesn't make sense. Did you copy-n-paste the error message without any changes? I would expect the filename to be `C:\dev\ros2_master\install\_local_setup_util_bat.py` instead.

Can you share the content of that specific file?

**Comment by Sleazey** [comment]
Hello Dirk:
I seem to have resolved the problem.

I completely wiped out all directories involved, down to bare metal so to speak.

I rebooted my vm system, then retrieved all of the ros2 projects from our local copy.
I reran the colcon build, with none of our local changes installed in the ros2 code.

This build was completely successful, and the "call C:\dev\ros2_master\install\setup.bat" completed successfully with no problems.

I will be re-applying our local changes in small portions, to see if I can identify a problem with our code.

Sorry for what seems to be a false alarm.
Thanks!
