### ISSUE TITLE
Symlink install option in Python packages overwrites data files in source directory

### ISSUE THREAD

**Issue by luca-della-vedova** [colcon/colcon-core#300]
We are building a Python - ROS2 package with colcon and noticed that whenever we use the --symlink-install option "some" of the data files in the source directory of our package get overwritten and become symlinks pointing to themselves, effectively breaking the source package.

We noticed this behavior with the [following package](https://github.com/osrf/traffic_editor/) (master branch), steps to reproduce:

- Create a colcon workspace, clone the package into src directory
- Source ROS2 eloquent
- Run colcon build --symlink-install

Command output:

```Starting >>> building_map_msgs
Starting >>> traffic_editor
[Processing: building_map_msgs, traffic_editor]                                                               
Finished <<< building_map_msgs [31.7s]                                                                         
Starting >>> building_map_tools
Finished <<< traffic_editor [32.0s]                                                                 
--- stderr: building_map_tools                    
error: can't copy 'building_map_generators/textures/blue_linoleum.png': doesn't exist or not a regular file
---
Failed   <<< building_map_tools	[ Exited with code 1 ]
                                 
Summary: 2 packages finished [32.9s]
  1 package failed: building_map_tools
  1 package had stderr output: building_map_tools
```
Now when checking the source directory:
```
cd src/traffic_editor
git status
```
This is the output
```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	typechange: building_map_tools/building_map_generators/textures/blue_linoleum.png
	typechange: building_map_tools/building_map_generators/textures/blue_linoleum_high_contrast.png
	typechange: building_map_tools/building_map_generators/textures/wall.png

no changes added to commit (use "git add" and/or "git commit -a")
```
The data files became symlinks pointing to themselves.

I tried to have a look at the code that is doing the linking and copying [here](https://github.com/colcon/colcon-core/blob/master/colcon_core/task/python/build.py#L221) but when I added a few debug print statements I noticed that the files in the build space exist even before that part of the code runs, so got a bit lost.

Something interesting I found is that if the data files are in the same folder as the setup.py the wrong behavior does not occur and everything works fine!
```
cd src/traffic_editor/building_map_tools
cp building_map_generators/textures/* .
vim setup.py # Edit the data files path to point to package root directory
```

If you have any suggestion on what might be wrong I can have a look as well.

Cheers
/Luca

**Comment by dirk-thomas** [comment]
Thank you for the report. I was able to reproduce the problem with the provided steps. Please see #301 for the proposed fix.
