### ISSUE TITLE
Colcon test terminates when ctrl-c is sent to a (child) subprocess on Windows

### ISSUE THREAD

**Issue by piraka9011** [colcon/colcon-core#303]
I am currently writing E2E tests for rosbag2 using pytest. I am able to run the E2E tests successfully without the parent process dying using pytest independently. 

The test involves spawning a subprocess with `process_handle = subprocess.Popen()`and terminating it with `process_handle.send_signal(signal.CTRL_C_EVENT)`.

When the process terminates, it kills `colcon test` with an output of `Aborted`. Is there a mechanism to handle signals with colcon test? I have tried various combinations of spawning the subprocess with `Popen()` to avoid this.

* `shell=True`
* `creationflags`:
  * `CREATE_NEW_CONSOLE`
  * `CREATE_NEW_PROCESS_GROUP`
  * `DETACHED_PROCESS`

as well as creating signal handlers and wrapping things in `try`/`except` blocks.

**Comment by dirk-thomas** [comment]
When you `Ctrl-C` a run of `colcon test` the logic catches all the aborted tests which should return with `SIGINT` and labels them as `aborted`. So if your test process returns with `SIGINT` that is the reason why you see it labeled that way.

Assuming you use `pytest` the question is why does it return `SIGINT`?

Sharing a reproducible example might help to figure out what is happening.

**Comment by piraka9011** [comment]
> Assuming you use `pytest` the question is why does it return `SIGINT`?

It doesn't. When I run `pytest test_end_to_end.py`, it is able to:
* spawn and execute a new process
* send a signal to terminate it (`SIGINT`/`CTRL_C_EVENT`)
* complete successfully (Reading files, making assertions, etc.) returning a success

> Sharing a reproducible example might help to figure out what is happening.

I will update this comment with a link to the branch with rosbag2 test that you can try on your own.

**Comment by dirk-thomas** [comment]
The referenced branch seems to lack files and fails to build:

```
CMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:158 (message):
  ament_cmake_symlink_install_files() can't find
  '/tmp/ws/src/rosbag2/rosbag2_tests/test/rosbag2_tests/command_wrapper.py'
Call Stack (most recent call first):
  ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:314 (ament_cmake_symlink_install_files)
  cmake_install.cmake:41 (include)
```

**Comment by piraka9011** [comment]
@dirk-thomas resolved. Can you please try again?

You can run the test without `colcon test` using `pytest test_compression_with_splitting.py`

**Comment by dirk-thomas** [comment]
On Linux `colcon test --packages-select rosbag2_tests` passed just fine for me (I skipped some of the linters which didn't pass).


I don't have a Windows machine at hand but I would suspect the current approach (sending a SIGINT and expecting only one subprocesses to receive it) isn't supported: see e.g. https://stackoverflow.com/questions/7085604/sending-c-to-python-subprocess-objects-on-windows

Have you tried to customize your test (not `colcon`) to pass `CREATE_NEW_PROCESS_GROUP` for the new subprocess (see https://stackoverflow.com/questions/40762545/how-to-send-a-ctrlc-sigint-to-a-subprocess-in-windows)?

* https://github.com/aws-ros-dev/rosbag2/blob/224d5079d6baa39c274e7ca16763baf69cb5c3a2/rosbag2_tests/test/rosbag2_tests/test_compression_with_splitting.py#L91

    ```
    try:
        creationflags = subprocess.CREATE_NEW_PROCESS_GROUP
    except AttributeError:
        creationflags = 0
    process_handle = subprocess.Popen(command, creationflags=creationflags)
    ```

* And I would guess you also need to change https://github.com/aws-ros-dev/rosbag2/blob/224d5079d6baa39c274e7ca16763baf69cb5c3a2/rosbag2_tests/test/rosbag2_tests/test_compression_with_splitting.py#L108 to:

    ```
    process_handle.send_signal(signal.CTRL_BREAK_EVENT)
    ```

**Comment by piraka9011** [comment]
> On Linux colcon test --packages-select rosbag2_tests passed just fine for me

Which is expected since it sends a `SIGINT` which is supported on linux :)

> Have you tried to customize your test (not colcon) to pass CREATE_NEW_PROCESS_GROUP for the new subprocess 

Yes, I have tried the following creation flags as outlined in my first post including different permutations of them:

* `shell=True`
* `creationflags`:
  * `CREATE_NEW_CONSOLE` (with `CREATE_NO_WINDOW`)
  * `CREATE_NEW_PROCESS_GROUP`  (with `CREATE_NO_WINDOW`)
  * `DETACHED_PROCESS`  (with `CREATE_NO_WINDOW`)

They either result in:

* Killing `colcon` with it
* Becoming detached and unable to receive a `CTRL_C_EVENT` (See the MS docs for [`GenerateConsoleCtrlEvent`](https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent) which is what python uses under the hood and the section on `CTRL_C_EVENT`).



> I don't have a Windows machine at hand but I would suspect the current approach (sending a SIGINT and expecting only one subprocesses to receive it) isn't supported

Not with `SIGINT` but  `CTRL_C_EVENT` is supported. If I use `CTRL_BREAK_EVENT`, then the process is killed with Window's `Terminate()` no chance for it to clean up after itself (in this case, close the database and write metadata to disk) causing the test to fail.

I think `colcon test` handles `SIGINT` just fine. Maybe there needs to be handler for `CTRL_C_EVENT` as well if the system is running Windows?

Also I already saw the [SA Link](https://stackoverflow.com/questions/7085604/sending-c-to-python-subprocess-objects-on-windows) and tried to use their approach by having a wrapper tool that executes the command but it still kills `colcon` (that was what CMakeLists was originally trying to install but failed since I forgot to remove it).

**Comment by piraka9011** [comment]
I'm not familiar with `colcon` codebase, but maybe adding a signal handler [here](https://github.com/colcon/colcon-core/blob/23d3c3031a31632c432460b566a227f9a256040e/colcon_core/executor/__init__.py#L265) for a `CTRL_C_EVENT` when executing a command could be a potential solution?

**Comment by dirk-thomas** [comment]
I am not even sure this needs to be worked around by `colcon`. I would assume you can apply whatever workaround is necessary to the subprocess invocation in your test.

Once that works we could revisit if a similar patch is useful / necessary in `colcon`.

**Comment by dirk-thomas** [comment]
@piraka9011 Any update on this?

**Comment by piraka9011** [comment]
I am going to try using the `launch_testing` tools for running the tests (similar to `ros2topic`'s tests) and see if that resolves handling `CTRL_C_EVENT`'s on Windows.

You can close this issue if you want in the meantime and I will re-open if necessary.
