### ISSUE TITLE
Bad call to os.kill

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#308]
A call to `os.kill` is missing its first argument. This is causing an error for me locally (though for some reason not in CI?)

```
FAILED   [ 28%]Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\dan\Documents\colcon\src\colcon-core\test\test_executor_sequential.py", line 179, in delayed_sigint
    os.kill(signal.CTRL_C_EVENT)
TypeError: kill() takes exactly 2 arguments (1 given)

test\test_executor_sequential.py:156 (test_sequential_keyboard_interrupt)
0 != <Signals.SIGINT: 2>
```

https://github.com/colcon/colcon-core/blob/0b5ec3d7ba3664ceb5609617bef3b6ad6dffe111/test/test_executor_sequential.py#L178-L179

**Comment by dirk-thomas** [comment]
The reason is that the test is being skipped on AppVeyor: see https://github.com/colcon/colcon-core/blob/0b5ec3d7ba3664ceb5609617bef3b6ad6dffe111/test/test_executor_sequential.py#L160-L163
