### ISSUE TITLE
colcon-ed package as replacement for rosed

### ISSUE THREAD

**Issue by Briancbn** [colcon/colcon-core#343]
A follow up on https://github.com/ros2/ros2cli/issues/483

I have written a simple package for `colcon-ed` [here](https://github.com/Briancbn/colcon-ed).

The usage is the same as rosed with 
```
colcon edit <package_name> <filename>
```
It has the following features
- [x] Autocomplete packages (using `package_discover`)
- [x] Autocomplete files (I didn't use the extension point for this because I don't have access to already parsed arg in the extension point)
- [x] Ignore hidden folders and files, I also added in *.pyc
- [x] Use `vim` by default if `$EDITOR` environment variable is not set or set to empty, otherwise run `$EDITOR <file_path>` is if is set.
- [x] Choose which file to edit when there are multiple files under the same name within a package.

Features not supported yet
- [ ] Windows support (I don't have a Windows machine to test on)

Please let me know if colcon is interested to have this as a repository or if there are any more features needed. Since I am new here, I don't know what is needed, I have the static analysis and CI setup as the other packages here.

**Comment by dirk-thomas** [comment]
Sounds good. Based on the [recommendation](https://colcon.readthedocs.io/en/released/developer/contribution.html#new-packages-extensions) I suggest you transfer the repository to my user name and I will then transfer the repo to the `colcon` org unit.

You will have full admin access to the repo after the transfer and can setup CI as you see fit, handle incoming tickets, and do releases to PyPI on your own schedule. To create a Debian package for new releases someone with access to the ROS apt repo needs to be involved. Please feel free to mention me on a future ticket asking to create a Debian package for a tagged version of this package.

**Comment by Briancbn** [comment]
@dirk-thomas Hi, I have initiated the repo transfer to your account.

**Comment by dirk-thomas** [comment]
I have moved the repo and you should have gotten an invite: https://github.com/colcon/colcon-ed/

I also created a few ticket for minor cleanups / fixes.
