### ISSUE TITLE
Vanilla CMake packages - correct CMAKE_PREFIX_PATH in dependencies

### ISSUE THREAD

**Issue by sebastian8000** [colcon/colcon-core#354]
I am trying to use colcon with vanilla CMake (without cmake-ament and ROS).

In a minimal example I have two packages, where package B contains an executable "app" which depends on "lib_a" from package A:

ws
|-package_a
|--include/lib_a.h
|--src/lib_a.cc
|--CMakeLists.txt
|--colcon.pkg
|
|-package_b
|--src/app.cc    (uses lib_a)
|--CMakeLists.txt    (with FindPackage(LibA REQUIRED))
|--colcon.pkg    (with "build-dependencies": ["package_a"])

CMakeLists.txt from "package_a" exports and installs a target "pkg_a::lib_a" in share/cmake/LibAConfig.cmake and installs the include folder and the lib.

When I build and install "package_a" manually with CMake in the first step and in a second step build "package_b" manually with CMake passing CMAKE_PREFIX_PATH to LibAConfig.cmake from step 1 everything works like expected.

I tried to build both packages automatically with colcon but failed.

The dependency graph (colcon graph) looks correct, but apparently when colcon calls CMake to configure and build package_b, it doesn't pass the CMAKE_PREFIX_PATH pointing to install/package_a/share/cmake. 

The install folder after calling colcon build looks like this:

ws
|-install
|--package_a
|---include
|----lib_a.h
|---lib
|----liblib_a.a
|---share
|----package_a
|-----hock
|------...
|-----package.bash
|-----...
|----cmake
|-----LibAConfig.cmake
|----colcon-core
|------packages
|-------package_a
|--local_setup.bash
|--....

From the documentation it is not clear how I can tell colcon to add the correct paths to the CMAKE_PREFIX_PATH from its dependencies.
Does colcon crawl the folders for "*Config.cmake" on itself files or do I have to give them explicitly somewhere?

**Comment by dirk-thomas** [comment]
> when colcon calls CMake to configure and build package_b, it doesn't pass the CMAKE_PREFIX_PATH pointing to install/package_a/share/cmake.

`colcon` prepends the "install prefix" of `package_a` when downstream packages like `package_b` are processed. That install prefix is `install/package_a`. You can double check that by outputting the environment variable in the CMake code of `package_b`.

The [CMake documentation](https://cmake.org/cmake/help/v3.17/command/find_package.html#search-procedure) describes in which subdirectories of the provided prefix paths it searches for CMake config files. `share/cmake` is not one of them.

**Comment by sebastian8000** [comment]
Thanks a lot. That solved my problem.
