### ISSUE TITLE
Seemingly infinite loop when building custom ROS2 message with long, incorrect parameter name

### ISSUE THREAD

**Issue by cnboonhan94** [colcon/colcon-core#364]
Environment:
ROS2 Foxy
Following Tutorial: https://index.ros.org/doc/ros2/Tutorials/Custom-ROS2-Interfaces/#create-custom-definitions

I was following the above tutorial to create a custom message. When defining the message (specifically [here](https://index.ros.org/doc/ros2/Tutorials/Custom-ROS2-Interfaces/#msg-definition)) i changed `int64 num` into `string txt_msg_autoflow_added_to_current_ventilation_mode' `.

There are two notable differences in this change. One, the length of the variable is increased. Second, there is an illegal character `'`. When building this package, `colcon` seems to be stuck in an infinite loop.

```
# Aborting after about 9 minutes 
Starting >>> tutorial_interfaces
[Processing: tutorial_interfaces]                         
[Processing: tutorial_interfaces]                                 
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
[Processing: tutorial_interfaces]                                   
Aborted  <<< tutorial_interfaces [9min 25s]     
```
If the name is shortened, such as `mode'`, i get the correct error flag:
```
 NameError: '_mode'' is an invalid field name.  It should have the pattern
  '^[a-z]([a-z0-9_]?[a-z0-9]+)*$'

```

so it seems the length of the parameter name has to do if an infinite loop occurs or not.

**Comment by dirk-thomas** [comment]
The problem is not related to `colcon` but the logic parsing the `.msg` file which is implemented in the ROS package [rosidl_adapter](https://github.com/ros2/rosidl/tree/master/rosidl_adapter).

Please see ros2/rosidl#508 for the proposed patch.
