### ISSUE TITLE
Warn when building outside of workspace root

### ISSUE THREAD

**Issue by SebastianGrans** [colcon/colcon-core#366]
I'm relatively new to ROS and I sometime find myself accidentally running `colcon build` in the wrong folder, i.e. not in the worspace root folder. This leads to `build`, `log`, and `install` folders in the wrong locations.   

I have two ideas on how this could be resolved: 

1. Warn and abort the build
2. Notify, but automatically build in the root folder

Either feature would also require some kind of `force` flag.
What do you think of this?

**Comment by dirk-thomas** [comment]
Duplicate of #139.

**Comment by SebastianGrans** [comment]
It seems like I need to hone my searching abilities. Thanks!
