### ISSUE TITLE
Provide a 'clean' verb

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#37]
to delete `build` `install` and `log` folder.

Once the notion of profile is there it could delete the folders corresponding to that profile rather than the default folders

**Comment by dirk-thomas** [comment]
I think we all agree that the functionality described in this ticket is useful and should be added.

The point @tfoote is trying to make is that `clean` is a target in Makefiles generated by CMake. And its semantic is different: it removes build artifacts but it doesn't remove anythin else like Makefiles, CMake cache, etc. Therefore it might be better to use a different term.

**Comment by tfoote** [comment]
How about `clean` that just passes through to the default Makefile/CMake generated targets. And an additional verb `wipe` or `expunge` which will remove the installed contents too. We could make those shortcuts for a fully named verb. `wipe-install` or `expunge-install` or if it's in long form `erase-install` could also work. And these more powerful verbs will chain through and call `clean` too.

**Comment by dirk-thomas** [comment]
> How about clean that just passes through to the default Makefile/CMake generated targets.

That is already possible with `colcon build --cmake-target clean`. So I don't see a need to elevate it into a verb.

**Comment by Theosakamg** [comment]
> That is already possible with colcon build --cmake-target clean. So I don't see a need to elevate it into a verb.

@dirk-thomas in case of other sub-system than cmake ? (eg. Gradle...)
It possible to apply the same model with `colcon build --gradle-task clean`.
But in case of multi-packages (mix of cmake and gradle) you need to pass `colcon build --cmake-target clean --gradle-task clean` ?

And in case of gradle (seem to be same for cmake), target clean only `rm -rf` the build folder and not make a build after. it was disruptif with verb build.

_(just a point of view of novice user.)_

**Comment by dirk-thomas** [comment]
I am not familiar with Gradle and don't know what it exactly does when running the `clean` "target". In the case of CMake / Make the `clean` target only removes the object files / generated files. It does *not* remove the build directory, e.g. the `CMakeCache.txt` file remains. It also doesn't affect the install space.

For the `clean` verb described in this ticket the scope would be to allow removing the actual build and install directories of a package (basically "rolling back" the `build` step which was run before).

For the case of invoking the existing `clean` target of some build systems I think the "mixin" approach described in https://github.com/colcon/colcon-core/issues/94#issuecomment-410057787 would be more suited.

**Comment by dirk-thomas** [comment]
> For the case of invoking the existing `clean` target of some build systems I think the "mixin" approach described in #94 (comment) would be more suited.

The mixin concept is now available through [colcon-mixin](https://github.com/colcon/colcon-mixin).

**Comment by scpeters** [comment]
I hear @tfoote's point that `catkin clean` is different than `make clean`, but it would be easier for me as a user if it worked the same way as `catkin-tools`. For me, it's more confusing for `colcon clean` to be different from `catkin clean` than if it's different from `make clean`.

**Comment by koenlek** [comment]
I agree with @scpeters, I'd prefer clean to work like it did in catkin tools.

An important point of running clean is that it clears caches. As far as I know, install space will also have the problem that old files won't be removed. Let's say I used to have a node `bar` in my `foo_pkg`, but that I renamed `bar` to `bar2`, then after subsequent builds, the install space would have both a `bar` and `bar2` node.

**Comment by tprk77** [comment]
Also agree with @scpeters. An analogous command to `catkin clean -y` would be ideal, in my opinion.

**Comment by mikepurvis** [comment]
Note that `catkin clean` although convenient has some goofiness going on behind the scenes. Basically, it's two totally different behaviours depending what you invoke:

- `catkin clean` deletes the build, logs, devel, and install folders, if they exist.
- `catkin clean mypackage` deletes build/mypackage and if symlink devel is enabled, removes the generated files corresponding to the particular listed package(s).

Not to say that these aren't both pretty convenient, but for implementation and user sanity, I would support them having different names.

**Comment by scpeters** [comment]
> Note that `catkin clean` although convenient has some goofiness going on behind the scenes. Basically, it's two totally different behaviours depending what you invoke:

Perhaps separate verbs?

* `catkin clean-workspace`
* `catkin clean-package`

**Comment by danthony06** [comment]
Is anyone interested in reviving this work? After doing some ROS 2 development, I'd really appreciate this functionality.

**Comment by ruffsl** [comment]
> Perhaps separate verbs?
> 
> * `catkin clean-workspace`
> * `catkin clean-package`

Hey folks! I made a quick implementation by coding this into two subverbs, allowing users to clean base folders within a workspace or on a per package bases. You can check it out and try it yourself here:

https://github.com/ruffsl/colcon-clean/pull/4

```
colcon clean --help
colcon clean workspace --help
colcon clean packages --help
```

Perhaps we could upstream this into the colcon org, and bundle it up with colcon-common after some iterations and PRs?

**Comment by ruffsl** [comment]
For potential uses of `colcon clean`, here is an example where the `packages` subverb is used to clean the respective install and test result bases for stale packages and keep CI cache sanitary:

https://github.com/ros-planning/navigation2/pull/2399

**Comment by AndyZe** [comment]
This reminds me of Bill Gates admitting Ctrl + Alt + Delete was a mistake. Let's admit it:  `colcon clean` would be really useful and we should probably overlook the quibbles here and make it happen

**Comment by ruffsl** [comment]
Has anyone had the chance to try out the `colcon clean` extension I posted about above?
I have since added a full readme with documentation on it's current functionality:
https://github.com/ruffsl/colcon-clean 

Perhaps we could migrate the extension repo to this colcon org and release it upstream. I think the scantree dependency for fast file path globbing may be the only issue, but perhaps that could be swapped an alternate regex approach.

**Comment by scpeters** [comment]
@cottsay what is the procedure for adding https://github.com/ruffsl/colcon-clean to the `colcon` org?

**Comment by tfoote** [comment]
It looks like @ruffsl's implementation with specific subcommands resolves my worries about clarity of the command.

**Comment by ooeygui** [comment]
I started going down the path of adding `ROS: Clean` to the Visual Studio Code ROS Extension per https://github.com/ms-iot/vscode-ros/issues/554. Would love to see @ruffsl's implementation adopted in colcon instead of brute forcing it from the extension.

**Comment by kledom** [comment]
@cottsay Friendly ping!
Any plans to make colcon-clean installable via apt?

**Comment by cottsay** [comment]
@ruffsl - if you'd like to proceed with moving `colcon-clean` under the `colcon` org and releasing debs for it, I can help make that happen. We should open a new issue to specifically track it. #493 is an example of a migration we completed previously.

**Comment by ruffsl** [comment]
@cottsay - I have opened two new tickets requesting the transfer and release of the new relevant extensions:

- https://github.com/colcon/colcon-core/issues/521
- https://github.com/colcon/colcon-core/issues/522

**Comment by ruffsl** [comment]
Hey folks, colcon-clean has been released, so I think we can finally close this ticket! https://github.com/colcon/colcon-core/issues/521#issuecomment-1353283776

```
$ sudo apt install python3-colcon-clean 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  python3-pathspec python3-scantree
The following NEW packages will be installed:
  python3-colcon-clean python3-pathspec python3-scantree
0 upgraded, 3 newly installed, 0 to remove and 16 not upgraded.
Need to get 51.5 kB of archives.
After this operation, 258 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 python3-pathspec all 0.9.0-1 [28.8 kB]
Get:2 http://packages.ros.org/ros2/ubuntu jammy/main amd64 python3-colcon-clean all 0.2.0-1 [9,898 B]
Get:3 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 python3-scantree all 0.0.1-2 [12.7 kB]
Fetched 51.5 kB in 1s (39.1 kB/s)        
Selecting previously unselected package python3-pathspec.
(Reading database ... 317982 files and directories currently installed.)
Preparing to unpack .../python3-pathspec_0.9.0-1_all.deb ...
Unpacking python3-pathspec (0.9.0-1) ...
Selecting previously unselected package python3-scantree.
Preparing to unpack .../python3-scantree_0.0.1-2_all.deb ...
Unpacking python3-scantree (0.0.1-2) ...
Selecting previously unselected package python3-colcon-clean.
Preparing to unpack .../python3-colcon-clean_0.2.0-1_all.deb ...
Unpacking python3-colcon-clean (0.2.0-1) ...
Setting up python3-pathspec (0.9.0-1) ...
Setting up python3-scantree (0.0.1-2) ...
Setting up python3-colcon-clean (0.2.0-1) ...

$ colcon clean --help
usage: colcon clean [-h] {packages,workspace} ...

Cleans package workspaces.

options:
  -h, --help            show this help message and exit

colcon clean verbs:
  packages              Clean packages in workspace
  workspace             Clean current workspace

  {packages,workspace}  call `colcon clean VERB -h` for specific help
```

**Comment by phil123456** [comment]
E: Unable to locate package python3-colcon-clean 
Ubuntu 20.04

**Comment by ruffsl** [comment]
> E: Unable to locate package python3-colcon-clean 
> Ubuntu 20.04

Due to missing python dependencies available with and after jammy, packing this extension couldn't be backported to Ubuntu focal.

https://github.com/colcon/colcon-core/issues/521

You could try still try using pip though.

**Comment by b-adkins** [comment]
I just wanted to add my user story and why I really want a `clean` verb of some sort. Normally, I would just delete `build` and `install` and be done with it, like I did in the past with `catkin`. But...

1. I use an IDE that requires files important for indexing to be in the `build` folder. This means if I delete the whole build folder, it will take significant time to set up again.
2. We haven't set up any install. so it's `build` and `install` folders in the standard `ros2_ws`.
3. I'm working on a robot code base of decent size and changes, including switching between my own feature branches, break the build often. Even something trivial like a file getting renamed can make some programs error out with "file not found" because it lingers as symbolic links.

When this happens, I have to do the following, _for each package name_. The package names are long and descriptive. 
```
cd ros2_ws
rm -r install/<prefix_custom_pkg_name> build/<prefix_custom_pkg_name>
rm -r install/<prefix_other_pkg_name> build/<prefix_other_pkg_name>
```
