### ISSUE TITLE
colcon package versions assume package already installed

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#374]
The way colcon package versions are specified relies on having the current module already installed.

https://github.com/colcon/colcon-core/blob/caee5e64608912f52e86f79de1cf53b8c34713df/setup.cfg#L1-L3

At build time, we have `version = attr: colcon_core.__version__` but there is no guarantee that `colcon_core` is in the python path at that time, 

When you install `colcon_core` with poetry, this shows up as a `ParseVersionError`:

```
C:\Users\dan\Documents\colcon-ws>poetry install
Updating dependencies
Resolving dependencies...

  ParseVersionError

  Unable to parse "attr: colcon_core.__version__".

  at ~\.poetry\lib\poetry\_vendor\py3.8\poetry\core\semver\version.py:206 in parse
      202│         except TypeError:
      203│             match = None
      204│
      205│         if match is None:
    → 206│             raise ParseVersionError('Unable to parse "{}".'.format(text))
      207│
      208│         text = text.rstrip(".")
      209│
      210│         major = int(match.group(1))
```

This setup is also known to cause trouble with setuptools:

https://github.com/pypa/setuptools/issues/1724

**Comment by rotu** [comment]
see https://packaging.python.org/guides/single-sourcing-package-version/ for some recommended ways to specify the package version which don't have this problem.

**Comment by dirk-thomas** [comment]
> The way colcon package versions are specified relies on having the current module already installed.
> ...
> At build time, we have `version = attr: colcon_core.__version__` but there is no guarantee that `colcon_core` is in the python path at that time, 
> ...
> see https://packaging.python.org/guides/single-sourcing-package-version/ for some recommended ways to specify the package version which don't have this problem.

The `colcon-core` package follows the best practice from the documentation you referenced - described in the note of option 1: using `attr: ...` in the `setup.cfg` file. As that documentation mentions you need at least version 46.4.0 of `setuptools` to not require the imported modules to be available which is why the build-from-source instructions mention that: https://colcon.readthedocs.io/en/released/developer/bootstrap.html#virtual-environment

What version of `setuptools` do you have when running into this problem? Assuming it is older than the above version does uodating it resolve the problem for you?

**Comment by rotu** [comment]
You’re right - it should work for setuptools 46.4.0. I somehow totally missed that note!

But setuptools is an install_requires and not a setup_requires and has a minimum version of 30.3.0. https://github.com/colcon/colcon-core/blob/caee5e64608912f52e86f79de1cf53b8c34713df/setup.cfg#L39

I suspect the issue is either that poetry does not implement the special AST analysis or that a clean venv does not have a bleeding edge setuptools. Will investigate deeper.

**Comment by rotu** [comment]
It's a super slippery bug to reproduce, and I'm having trouble pinning it down fully.

I think this might be a bug in `poetry` in that it takes a shortcut when comparing the package version against that in the lockfile, which bypasses the special behavior of setuptools.

I'm not sure if #381 will resolve the issue fully with `poetry` but I'll revisit if it doesn't.
