### ISSUE TITLE
Standalone package discovery

### ISSUE THREAD

**Issue by mikepurvis** [colcon/colcon-core#378]
Currently package discovery is tied pretty heavily to the `argparse.Namespace` return object. This is what it looked like for me to run that logic standalone:

```
from argparse import ArgumentParser
from colcon_core.package_discovery import discover_packages
from colcon_core.package_selection import add_arguments as add_packages_arguments
from colcon_core.package_identification import get_package_identification_extensions
from colcon_core.location import set_default_config_path

set_default_config_path(path="lol")
parser = ArgumentParser()
add_packages_arguments(parser)
args = parser.parse_args([])
extensions = get_package_identification_extensions()

# fiddle with args.bath_paths to look for packages in places other than the cwd
print(discover_packages(args, extensions))
```

I'm able to eliminate the actual argparse setup/call by just supplying the namespace object like so, but it was trial and error to figure out which attributes were actually needed:

```
args = argparse.Namespace(base_paths=['.'], ignore_user_meta=True, paths=None, metas=['./colcon.meta'])
extensions = get_package_identification_extensions()
print(discover_packages(args, extensions))
```

Is this something colcon could supply itself, either in code form or at least a documentation of which keys are required to be present on the args object? Or making it fall back to defaults when one is missing so that an empty object could be passed for `args`? If the defaults could be supplied somewhere accessible to both the consuming logic and the argparse setup, this approach could still remain dry.

Alternatively, should I just not feel bad about about just calling `parser.parse_args([])` to get whatever the defaults are and rolling with that?

**Comment by dirk-thomas** [comment]
> Is this something colcon could supply itself, either in code form or at least a documentation of which keys are required to be present on the args object?

Due to modular and highly extensible nature of `colcon` I am not sure that question can be answered statically. An extension can contribute arbitrary arguments and then also expect them to be present (if not explicitly written to check their existence before using it). But adding an API which can provide a `namespace` instance should be feasible.

> should I just not feel bad about about just calling parser.parse_args([]) to get whatever the defaults are and rolling with that?

I would assume such new API would pretty much do the same internally. So I don't think you have to feel bad calling `parse_args()`. The more important part to encapsulate in the API would be the construction and population of the `argparse` parser if you had the need to do that manually.

I think it would be good if you could share more details what exactly you are trying to achieve and which existing API you use for that and what parts are missing / you have to manually replicate.

**Comment by mikepurvis** [comment]
Thanks for the response. My use case is building a prototype of the concept described in https://github.com/ros-infrastructure/rosdistro/issues/146 (tentatively `colcon-distro`), which consumes `source` entries from a rosdistro's `distribution.yaml`, fetches them, and uses colcon's package discovery mechanism to find the packages contained therein, for later retrieval and use in a `rosinstaller_generator`-like tool.

Because one of my design goals is for this experiment is to cover many tags and tag-like objects in the rosdistro repo rather than just a single "present moment" state for each distribution (as `rosdistro` does), it is backed by a simple database instead of static yaml files. This means it is also a long-running server process and therefore does not fit well into colcon's verb-based execution model. So it's a fully separate entry-point, but obviously is importing the pieces of colcon which are relevant to what I'm doing. I'm also using colcon's package augmentation hook to supply additional metadata in some cases (which _should_ allow the main tool to remain free of CPR-proprietary details and therefore be releasable).

**Comment by mikepurvis** [comment]
I'm content just pre-cooking a Namespace object for my use cases, so unless there are others with an interest in this area, I think it's fine for this ticket to be closed.
