### ISSUE TITLE
Crash in _create_symlink on Windows

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#382]
Colcon had a puzzling crash running on Windows CI:

https://github.com/ros-tooling/action-ros-ci/pull/341/checks?check_run_id=1099569462#step:6:456

https://github.com/ros-tooling/action-ros-ci/pull/341/checks?check_run_id=1099569462

```
C:\Windows\system32\cmd.exe /E:ON /V:OFF /S /C call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64 & "C:\Program Files\Git\bin\bash.exe" -c "colcon build --event-handlers console_cohesion+ --packages-up-to ament_copyright  --cmake-args "
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.7.2
  ** Copyright (c) 2020 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x64'
  Traceback (most recent call last):
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\colcon.exe\__main__.py", line 7, in <module>
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\colcon_core\command.py", line 100, in main
      return _main(command_name=command_name, argv=argv)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\colcon_core\command.py", line 164, in _main
      create_log_path(args.verb_name)
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\colcon_core\location.py", line 186, in create_log_path
      path.parent / 'latest')
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\colcon_core\location.py", line 190, in _create_symlink
      if dst.exists():
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\pathlib.py", line 1361, in exists
      self.stat()
    File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\pathlib.py", line 1183, in stat
      return self._accessor.stat(self)
  PermissionError: [WinError 5] Access is denied: 'log\\latest'
##[error]The process 'C:\Windows\system32\cmd.exe' failed with exit code 1
```

Couple weird things here:

- While the error was in `_create_symlink`, it does not appear to have had the error while actually *creating* a symlink, but in a call to `Path.exists()`, when creating a symlink from `log/latest` to `log/latest_build`.
- Root cause is unknown but it seems like it might be a race condition since the process had *just* created the symlink from `log/latest_build` to the actual build log directory.
- This also might have to do with some caching behavior mentioned [here](https://docs.python.org/3.7/library/os.html#os.DirEntry.stat)

**Comment by dirk-thomas** [comment]
Please provide minimal reproducible steps.

**Comment by rotu** [comment]
I don't know how to reproduce this crash nor how to quantify how common it is.

One way to cause a similar crash is to try to create a symlink inside a parent folder without read access to that parent folder.

**Comment by dirk-thomas** [comment]
> One way to cause a similar crash is to try to create a symlink inside a parent folder without read access to that parent folder.

Can you please post concrete steps I can try to reproduce for this.

**Comment by rotu** [comment]
> Can you please post concrete steps I can try to reproduce for this.

Here's a way to reproduce it on Nix:

```
mkdir foo
chmod -x foo
ln -s baz foo/bar
```

Then `os.path.exists('baz')` will crash, and by extension, so would `colcon_core.location. _create_symlink('bork','baz')`

**Comment by dirk-thomas** [comment]
> Here's a way to reproduce it on Nix:

When executing three commands as shown the last one fails with: `ln: failed to access 'foo/bar': Permission denied`

After swapping the second and third line Python still doesn't crash for me but reports `False`.

**Comment by dirk-thomas** [comment]
Beside still needing a reproducible example please also fill a ticket upstream. The fact that `colcon list` fails but the action continues seems like pretty bad behavior to me.

**Comment by rotu** [comment]
> When executing three commands as shown the last one fails with: `ln: failed to access 'foo/bar': Permission denied`

Interesting ... I tried this on Mac, and I assumed Linux would behave similarly. Guess not! Maybe it even depends on the filesystem.

> The fact that colcon list fails but the action continues seems like pretty bad behavior to me.

Agreed. I didn’t even notice this until you pointed it out.

**Comment by cottsay** [comment]
Without any actionable way to reproduce the problem, I'm going to close this issue.
