### ISSUE TITLE
Not all python packages support egg_base

### ISSUE THREAD

**Issue by mikepurvis** [colcon/colcon-core#394]
A small leftover from https://github.com/colcon/colcon-core/pull/387#issuecomment-698937014 is that some Python packages from PyPI don't support the `egg_base` option. We can work on getting fixes push upstream to these (https://github.com/msoulier/tftpy/pull/114, https://github.com/npcole/npyscreen/pull/106), but it would be nice if colcon could detect this failure and retry without that option.

Reproduction:

```
git clone https://github.com/npcole/npyscreen
colcon build
```

Result:

```
Starting >>> python3-npyscreen
--- stderr: python3-npyscreen
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'egg_info'
---
Failed   <<< python3-npyscreen [0.72s, exited with code 1]
```

We've found a handful of python packages in our distribution which fail in this way.

**Comment by dirk-thomas** [comment]
Please see #396 which aims to add support for Python packages using `distutils`.
