### ISSUE TITLE
Shouldn't colcon fail if a dependency is missing

### ISSUE THREAD

**Issue by fred-apex-ai** [colcon/colcon-core#399]
Hello everyone,

thanks for building colcon. It helps quite a bit but there are still some rough edges

## current behavior

I was frustrated by the fact that when I have a `package.xml` for `my_pkg` and add a bogus dependency

   <depend>foo</depend>

that doesn't exist, then 

    colcon build --packages-select my_pkg

does **not** complain. Somewhere down the line one may encounter a missing include during compilation or any other error, seemingly unrelated to the root cause. It happened to me that the dependency was ignored due to a `COLCON_IGNORE` file but I checked it also happens with no dependency available at all.

Is there a good reason for this behavior? It goes against the rule of thumb to fail early.

### workaround 
If I had the suspicion that a package was not found, I could verify by running 

    colcon list

and check if `foo` is listed.

## Proposed behavior

`colcon` should not invoke `cmake` to build but fail early if a dependency is missing or ignored, clearly stating that a dependency was not found. This would save developers a lot time while they are scratching their head.

**Comment by christophebedard** [comment]
> Is there a good reason for this behavior? It goes against the rule of thumb to fail early.

The dependency might not necessarily be in your workspace. It might not even be a package (with a `package.xml`): it could be an `apt` or `pip` dependency. Thus I don't think `colcon` can (or should) really easily check. It's not really up to colcon.

If you do `colcon build --packages-select foo` then it complains of course.

**Comment by mikepurvis** [comment]
Colcon can't tell this information, since sometimes a dependency is really mapping through rosdep to some system package— or maybe it's just a source checkout that was `make install`ed.

You could certainly implement some kind of dependency-auditing system, possibly as part of the build step, but definitely as separate verb. To do that, though, you'd need a way to supply the information into colcon about which deps are satisfied by existing system state.

**Comment by fred-apex-ai** [comment]
> apt or pip dependency
but when it comes to building, it has to pull in the dependencies, right? And if that fails, colcon will just continue??

> If you do `colcon build --packages-select foo` then it complains of course.

That's my point, colcon doesn't complain now but should complain. Maybe g++ or whoever complains at some point about a missing header. 

And if `colcon list` doesn't contain the package I depend on, why would `colcon build` continue? I don't know the internals but somehow this list of available packages is gathered and should be used to bail out before invoking cmake

**Comment by dirk-thomas** [comment]
> but when it comes to building, it has to pull in the dependencies, right?

Not really. If the dependency is outside of the workspace `colcon` excepts it to be usable which depending on the type can mean different things (e.g. be able to find headers, libraries, CMake config files / modules, Python packages / modules).

> And if colcon list doesn't contain the package I depend on, why would colcon build continue?

Because the packages in the workspace can declare plenty of dependencies which are *not* part of the workspace. And as the previous comments already describe `colcon` can't know how to check for them.

**Comment by fred-apex-ai** [comment]
> To implement the desired behavior you are describing colcon would need to be able to answer the question: "is the dependency foo available?" which it can't without a lot more semantic information about that dependency.

I see it's hard in the general case. What about the problem I ran into that a package was ignored. Then it doesn't need extra knowledge to report this as missing, right?

**Comment by dirk-thomas** [comment]
> What about the problem I ran into that a package was ignored.

**Comment by dirk-thomas** [comment]
> What about the problem I ran into that a package was ignored.

If a package is being ignored (either via a `CATKIN_IGNORE` file or using `--packages-ignore*`) the package isn't even returned from the discovery phase. So following part don't even know about the existence and therefore can't reason about it.

**Comment by mikepurvis** [comment]
Plus, there's a totally valid use-case for using the various ignore mechanisms to build only some packages from a particular repo where you know the others are in your underlay.

**Comment by fred-apex-ai** [comment]
@dirk-thomas So the conclusion for you is that nothing needs to be changed in colcon and for me that dependencies in `package.xml`  have to be checked manually for availability because colcon takes a hands-off aproach

**Comment by dirk-thomas** [comment]
> ... because colcon takes a hands-off aproach

I wouldn't phrase it like this. If 'colcon` could perform additional checks that would be nice. But as it stands there is a very significant part of knowledge / semantics missing in order to be able to do so. If you would like to contribute features towards such a goal that would be great.
