### ISSUE TITLE
Appveyer CI warning about scripts not in path

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#401]
Appveyer CI seems to have a misconfigured python. Python scripts are being installed outside the active PATH

https://ci.appveyor.com/project/dirk-thomas/colcon-core/builds/30033046

> WARNING: The scripts easy_install-3.8.exe and easy_install.exe are installed in 'C:\Python38-x64\Scripts' which is not on PATH.

> WARNING: The script humanfriendly.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script coloredlogs.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

>   WARNING: The script pycodestyle.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   WARNING: The script pyflakes.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   WARNING: The script flake8.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   WARNING: The script pydocstyle.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   ...
>   WARNING: The script isort.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   WARNING: The scripts epylint.exe, pylint.exe, pyreverse.exe and symilar.exe are installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>   WARNING: The scripts py.test.exe and pytest.exe are installed in 'C:\Python38-x64\Scripts' which is not on PATH.
>   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
>     Running setup.py install for coverage: started

>   WARNING: The script chardetect.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script codecov.exe is installed in 'C:\Python38-x64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by dirk-thomas** [comment]
Thanks for the report. Addressed by #402.
