### ISSUE TITLE
Colcon fails to build Python package if path to package contains symbolic links: "error in 'egg_base'"

### ISSUE THREAD

**Issue by schornakj** [colcon/colcon-core#404]
This issue was originally discussed in [this ROS Answers post](https://answers.ros.org/question/364060/colcon-fails-to-build-python-package-error-in-egg_base/).

I have two workspaces that share the same `src` directory using a symbolic link. This is so I can build the same packages from source in both Debug and Release mode without having to perform a clean build. After an `apt upgrade` last week, I started seeing this error:

```
$ colcon build --packages-up-to joint_state_publisher
Starting >>> joint_state_publisher
--- stderr: joint_state_publisher                   
error: error in 'egg_base' option: '../../../build/joint_state_publisher' does not exist or is not a directory
---
Failed   <<< joint_state_publisher [0.44s, exited with code 1]

Summary: 0 packages finished [0.76s]
  1 package failed: joint_state_publisher
  1 package had stderr output: joint_state_publisher
```

Discussion on ROS Answers showed that this issue is likely related to the presence of symbolic links in the path to the Python package being built.

Here is a test case to demonstrate failure while building a workspace in which the package directory is symlinked:
```
mkdir -p test/ws/src
cd test/ws/src
ros2 pkg create --build-type ament_python foo
cd ..
colcon build  # Succeeds
rm -rf build/ install/ log/
mv src/foo ../
ln -s $(pwd)/../foo src/foo
colcon build  # Fails with same error listed above
```

Building a workspace in which the entire `src` directory is symlinked to a different workspace's `src` directory also fails:
```
mkdir -p test_ws/src
cd test_ws/src
ros2 pkg create --build-type ament_python foo
cd ../..
mkdir test_link_ws
cd test_link_ws
ln -s ../test_ws/src src
cd ../test_link_ws
colcon build  # Fails with error listed above
```

However, if I build the workspace containing the `src` directory first, building the second workspace containing the link to `src`  will succeed:
```
mkdir -p test_ws/src
cd test_ws/src
ros2 pkg create --build-type ament_python foo
cd ../..
mkdir test_link_ws
cd test_link_ws
ln -s ../test_ws/src src
cd ../test_ws
colcon build  # Succeeds
cd ../test_link_ws
colcon build  # Succeeds
```

**Comment by ByLiZhao** [comment]
I encountered to this issue today too.  After checking the log, it appears that instead getting the real path (after resolving possible symbolic links), `colcon` just assumes that the path to a package does not contain symbolic links. So, if the python package is found at `./src/a_symlink/some_package/my_python_package`, `colcon` will look for the `build` directory with respect to the project root of `my_python_package` at `../../../../build`. 

BTW, with CMake, one can get the real path of a file using `get_filename_component(<var> Filename, REALPATH)`.

**Comment by VinceDT** [comment]
+1

**Comment by mikepurvis** [comment]
This is almost certainly a consequence of #387, but I'm not sure how to best resolve this from Python.

**Comment by cottsay** [comment]
Hi, please give #412 a try (it was already merged into master). I think it might resolve this issue.

**Comment by Timple** [comment]
It does!

Hopefully this gets released soon. Takes a while to end up on this thread.

**Comment by brennand** [comment]
When will this be merged into foxy?

**Comment by cottsay** [comment]
0.7.0 has been released.
