### ISSUE TITLE
python package --symlink-install is broken for config files

### ISSUE THREAD

**Issue by BrettRD** [colcon/colcon-core#407]
Building a python package containing launch and config files using `colcon build --symlink-install` results in the config and launch files getting copied into install/ instead of symlinked.
This seems to apply to anything listed under `data_files` in setup.py.

Doing the same with cmake results in symlinks in the install directory as expected.

There doesn't appear to be any documented way of getting config files symlinked using setup.py except for hacky workarounds involving hardcoded links in launch files that prevent clean packaging

Similar issues have been raised, but none were usefully resolved:
https://github.com/ros2/launch/issues/187
https://github.com/colcon/colcon-core/issues/169

**Comment by martimorta** [comment]
Hi,
I have seen there was this PR #223 trying to fix this issue, but it is not resolved yet.

**Comment by bijoua29** [comment]
So it looks like this issue has still not been fixed. Is symlink just broken for python packages or is there a workaround?

**Comment by Raamkishore** [comment]
Still doesn't work unfortunately.

**Comment by eMrazSVK** [comment]
Does not work until this day. I cannot even overcome this with supplying my package with `CMakeLists.txt` since only one build type is supported and my package is consisting purely of Python modules.

**Comment by KKSTB** [comment]
Seems converting a `ament_python` package to `ament_cmake_python` helps (example: https://github.com/IMRCLab/crazyswarm2/commit/fd778f30228ed87fa4ca49c1ed9274bfe98a8df7)
