### ISSUE TITLE
colcon test ctest timeout not working?

### ISSUE THREAD

**Issue by tylerjw** [colcon/colcon-core#408]
When I configure the timeout of a test through the cmake ament_add_gtest command it has no affect on the 60.0s timeout that colcon test has for each test when it runs ctest.  Even if I try to set the timeout through the --timeout or --test-timeout ctest args it also has no affect.

I have a test when built with debug symbols and run on a ci system is slightly longer than 60s when doing code coverage reporting.  Am I extending the test timeout incorrectly or is there no way to affect the timeout currently when using colcon test to run tests?

This is in the ros:foxy docker image I'm using for CI.

**Comment by dirk-thomas** [comment]
`colcon` only invokes `ctest` under the hood. If the configured timeout doesn't work please create a ticket in the repo providing the `ament_add_gtest` API which is https://github.com/ament/ament_cmake (and reference this ticket from there for future readers to find the follow up ticket).

**Comment by tylerjw** [comment]
@dirk-thomas thank you for the reply.  I posted an issue on ament_cmake here (https://github.com/ament/ament_cmake/issues/313) with what I think might be broken there.  The thing that I think might be broken with colcon test is that when I do something like this: `colcon test --ctest-args " --timeout 120"` I still get a timeout of 60.0s per test.  My problem might be not understanding where the timeout is being evaluated.  Is it in ctest (controlled by colcon), does it have somethign to do with ament_cmake, or is it some other layer entirely?  

I've searched through a bunch of source code and I can't find where this log line is comming from:

```
7: Test timeout computed to be: 60
```

Is that colcon, is it ctest, is it in the python launch wrapper generated by ament_cmake, is it in the executable created by cmake?

**Comment by dirk-thomas** [comment]
https://stackoverflow.com/questions/45009595/how-to-overwrite-ctest-default-timeout-1500-in-cmakelists-txt describes the difference between the default timeout (which can be configured using that command line option) and the timeout specifically configured for a test.

Based on the conversation in the referenced ticket I assume you have resolved your case and I will go ahead and close this ticket.

**Comment by tylerjw** [comment]
I'm still not sure what is sending that logline, but I no longer care because I have a way to control the timeout.  Now if only I could figure out how to modify some of these moveit tests so they don't take 5min to run a single test on a debug codecoverage build :facepalm: on the ci system.

Thank you for your help :smile:
