### ISSUE TITLE
cmake args being passes as project to build instead of being passed to cmake

### ISSUE THREAD

**Issue by jkordani** [colcon/colcon-core#429]
```
colcon build --cmake-args '-DCMAKE_EXPORT_COMPILE_COMMANDS=1' --cmake-args "--make-args -j8 -l8" --event-handler console_cohesion+ --packages-select my_project
Starting >>> my_project
--- output: my_project
CMake Error: The source directory "/path/to//my_project/--make-args -j8 -l8" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
---
--- stderr: my_project
CMake Error: The source directory "/path/to/my_project/--make-args -j8 -l8" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
---
Failed   <<< my_project [0.04s, exited with code 1]

```
What am I doing wrong?  I wish that colcon/cmake/whatever is in the chain passes -l down to make, because otherwise my cpu load blows up

**Comment by christophebedard** [comment]
did you try this?

```
colcon build --cmake-args "-DCMAKE_EXPORT_COMPILE_COMMANDS=1 --make-args -j8 -l8" --event-handler console_cohesion+ --packages-select my_project
```

**Comment by jkordani** [comment]
Yes I've done that,  same result

**Comment by christophebedard** [comment]
Weird, it works for me if I adapt `--packages-select my_project`.

Can you try adding a space at the beginning of the cmake args string? Like this:

```
colcon build --cmake-args " -DCMAKE_EXPORT_COMPILE_COMMANDS=1 --make-args -j8 -l8" --event-handler console_cohesion+ --packages-select my_project
```

Also, what version are you using? E.g. `pip3 list -v | grep colcon`

**Comment by jkordani** [comment]
That did it.  I was trying many different combinations.  What a weird error mode

**Comment by christophebedard** [comment]
It is documented in the `--help` output and here: https://colcon.readthedocs.io/en/released/reference/verb/build.html#cmake-specific-arguments

> **--cmake-args [* [* …]]**
>
> Pass arbitrary arguments to CMake projects. Arguments matching other options must be prefixed by a space, e.g. `--cmake-args " --help"`.

but yeah it's a bit confusing.
