### ISSUE TITLE
Create repository for colcon-ros-cargo

### ISSUE THREAD

**Issue by esteve** [colcon/colcon-core#435]
We already have colcon-cargo for pure Cargo projects, but we'd need another repo for `ament_cargo`, would it be possible to create `colcon-ros-cargo` and add @nnmm and me as admins? Thanks!

**Comment by nuclearsandwich** [comment]
https://github.com/colcon/colcon-ros-cargo/ has been created and maintainer invites have been dispatched. Please close this issue once both of you have confirmed your access.

**Comment by esteve** [comment]
@nuclearsandwich thanks. I have admin access for `colcon-cargo`, would it be possible to have the same access level for `colcon-ros-cargo`? Thanks

**Comment by nuclearsandwich** [comment]
> I have admin access for `colcon-cargo`, would it be possible to have the same access level for `colcon-ros-cargo`? Thanks

Yep, just changed for both you and @nnmm I default to maintain for everything to reduce the accidental/compromised deletion chance but there is enough of a [gap between Maintain and Admin](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) that it isn't really tenable to have no active admins on a project.

**Comment by esteve** [comment]
@nuclearsandwich thank you so much, closing this ticket now.
