### ISSUE TITLE
[Feture request] Per-repo cmake arg passing. 

### ISSUE THREAD

**Issue by ZhenshengLee** [colcon/colcon-core#442]
As for now, the only way that I know to pass cmake-arg to colcon is to using colcon cli, like

```sh
--cmake-args -DBUILD_TESTING=ON -DPERFORMANCE_TEST_ICEORYX_ENABLED=ON \
    -DPERFORMANCE_TEST_CYCLONEDDS_ENABLED=OFF -DPERFORMANCE_TEST_FASTRTPS_ENABLED=OFF\
    -DPERFORMANCE_TEST_RCLCPP_EVENTS_EXECUTOR_ENABLED=ON
```

But, there are always warnings below.

```sh
Finished <<< test_cli_remapping [15.6s]                                                                                                                  
--- stderr: iceoryx_ros2_bridge                                                                                                                              
CMake Warning:
  Manually-specified variables were not used by the project:

    PERFORMANCE_TEST_CYCLONEDDS_ENABLED
    PERFORMANCE_TEST_FASTRTPS_ENABLED
    PERFORMANCE_TEST_ICEORYX_ENABLED
    PERFORMANCE_TEST_RCLCPP_EVENTS_EXECUTOR_ENABLED


---
```

Does colcol have any solution with this?

Thanks.

**Comment by christophebedard** [comment]
You can use the `--no-warn-unused-cli` CMake option using `--cmake-args --no-warn-unused-cli` with `colcon build`.

**Comment by christophebedard** [comment]
That's strictly for getting rid of the warning, but having a way to pass package-specific CMake args would be interesting! Maybe like `--cmake-args-pkg PACKAGE_NAME ARG [ARG [ARG ...]]`.

It's probably not common, but I have come across a set of packages that have a CMake option with the same name and for which setting different values would be a valid use-case. All the vendor packages have a `FORCE_BUILD_VENDOR_PKG` option and don't have a package-specific option like `FORCE_BUILD_VENDOR_PKG_${VENDOR_PKG_NAME}`.

**Comment by mikepurvis** [comment]
You can provide per-package settings using `.meta` files: https://colcon.readthedocs.io/en/released/user/configuration.html#meta-files

Understandably, there isn't a mechanism for supplying this level of detail right on the command line, but having it able to be supplied via files should give you the flexibility you need to either store your per-package build configs in a separate repository, or create a tool that generates them based on other information specific to your org, or whatever.

**Comment by ZhenshengLee** [comment]
> You can provide per-package settings using `.meta` files: https://colcon.readthedocs.io/en/released/user/configuration.html#meta-files
> 
> Understandably, there isn't a mechanism for supplying this level of detail right on the command line, but having it able to be supplied via files should give you the flexibility you need to either store your per-package build configs in a separate repository, or create a tool that generates them based on other information specific to your org, or whatever.

Thanks for your reply. @mikepurvis 

I've tried this earlier but failed because I did not find a scheme in the docs website, could you give more details about how to write this meta file?

**Comment by christophebedard** [comment]
> I've tried this earlier but failed because I did not find a scheme in the docs website, could you give more details about how to write this meta file?

I agree that it's a bit hard to figure out what it means without an example. I found one example of a `.meta` file here: https://github.com/eProsima/Fast-DDS/blob/master/.github/workflows/statistics_module.meta

There's also `colcon.pkg`: https://colcon.readthedocs.io/en/released/user/configuration.html#colcon-pkg-files. These are similar to `.meta` files, but they're package-specific and must be placed in the package's root directory. Some examples:

* https://github.com/ros2/ros2cli/blob/6cbe07025506233120703bc88e6a2123615e2e97/ros2cli/colcon.pkg
* https://github.com/ament/ament_index/blob/2d6efc545159c4d1ea0b7b827bbd7efa6a34646f/ament_index_python/colcon.pkg
* https://github.com/eclipse-cyclonedds/cyclonedds/blob/f879dc0ef56eb00857c0cbb66ee87c577ff527e8/colcon.pkg
* https://github.com/eProsima/Fast-DDS/blob/master/colcon.pkg

**Comment by ZhenshengLee** [comment]
Thanks for all, closing this.

**Comment by traversaro** [comment]
> > I've tried this earlier but failed because I did not find a scheme in the docs website, could you give more details about how to write this meta file?
> 
> I agree that it's a bit hard to figure out what it means without an example. I found one example of a `.meta` file here: https://github.com/eProsima/Fast-DDS/blob/master/.github/workflows/statistics_module.meta

For people arriving here from the future, a permalink to this file is https://github.com/eProsima/Fast-DDS/blob/v2.3.4/.github/workflows/statistics_module.meta .
