### ISSUE TITLE
[enhancement] add a colcon ignore cmd argument for permanently ignoring packages

### ISSUE THREAD

**Issue by gramss** [colcon/colcon-core#447]
Hello,

I was thinking about this use case:

I'm building a base docker environment for project A (with 3-5 packages) which uses for example only one package from project B (like projectB-msgs).

I want to protect novice programmers using this environment and building further packages from project B that they do not need. But I also do not want to change project B to only build that one package by default.

-------

The feature I would like to request would probably work like that:

`colcon ignore --packages-other-than <package-list>`
Which would add a `COLCON_IGNORE` file in each package that is not in that list. Additionally, it also takes a path like `[--ignore-path <src/projectB>]` to only ignore packages from a certain project/"namespace"/sub-folder. 

------

Disclaimer:
The best way would probably be to have all packages from projectB be released through Bloom as individual packages. This way I would only need to install `apt install ros2-<distro>-projectB-msgs` and everything would be fine.
I'm asking this if there is some valid use for this before just implementing it and getting the PR rejected.

For me there certainly is a valid use case as we are building up a bigger software architecture and trying some bits out here and there before publishing anything as a bloom package.
Also, all the packages are not in the same workspace due to dependency collisions which are handled fine through docker. That stops me from just compiling everything and be happy.

Eager to hear your feedback on this one. Cheers!

**Comment by sloretz** [comment]
Interesting idea. I would recommend starting by making a new class inheriting from `VerbExtensionPoint` in a new python package (called `colcon-ignore`?). Then I would recommend using the existing package discovery and selection arguments.

`--packages-other-than` sounds a lot like `--packages-skip`. If you have a ROS 2 workspace, try `colcon list` and `colcon list --packages-skip zstd_vendor`  to see the last package get skipped. `--ignore-path` may already be covered by the package discovery argument `--base-paths`. It controls where `colcon` looks for packages. If you have a ROS 2 workspace, try `colcon list --base-paths src/ros2/rcl`; it will show all packages (and only those packages) in that folder. That would be a good way to control which packages are chosen to be ignored.

I think a good example to follow is `colcon-package-information` and how it implements `colcon list`.

https://github.com/colcon/colcon-package-information/blob/3fedb42f70337dd62fe0db1b7afed7f8cf82306f/colcon_package_information/verb/list.py#L14



https://github.com/colcon/colcon-package-information/blob/3fedb42f70337dd62fe0db1b7afed7f8cf82306f/setup.cfg#L61

**Comment by sloretz** [comment]
Once that's working in a new package in a new repo, you can release it on PyPI for anyone to use. No need to worry about a PR to `colcon-core` being rejected :)

**Comment by cottsay** [comment]
Another way to solve this problem might be to use a colcon [defaults.yaml](https://colcon.readthedocs.io/en/released/user/configuration.html#defaults-yaml) that looks something like this:
```json
{
  "build": {
    "packages-ignore": ["projectB-msgs"]
  },
  "test": {
    "packages-ignore": ["projectB-msgs"]
  }
}
```

That would cause both the `build` and `test` verbose to automatically ignore the listed packages unless the user specifies something else for the `--packages-ignore` argument. It isn't perfect, but it also doesn't require any new code.

**Comment by cottsay** [comment]
Closing this since the functionality should be implemented outside of `colcon-core`.
