### ISSUE TITLE
symlink-install created a broken link from a install to src directory

### ISSUE THREAD

**Issue by tylerjw** [colcon/colcon-core#455]
As pointed out [here](https://github.com/ros2/rcl_interfaces/issues/131) when building with symlink-install a symlink is being created that points to a directory that doesn't exist, causing a build error:

```
> cd /home/tyler/code/rolling/ws_moveit_source/install-tsan/rosidl_typesupport_c/lib/rosidl_typesupport_c/
> ll
total 4.0K
lrwxrwxrwx 1 tyler tyler 110 Nov 26 13:02 rosidl_typesupport_c -> /home/tyler/code/rolling/ws_moveit_source/src/rosidl_typesupport/rosidl_typesupport_c/bin/rosidl_typesupport_c
```

**Comment by cottsay** [comment]
@tylerjw I know this is a really old ticket, but I just tried the original command and I can't reproduce the problem. It is likely this was a problem in `ament_cmake` somewhere - colcon pretty much just tells `ament_cmake` to do it's thing:
https://github.com/colcon/colcon-ros/blob/6d65444f52b1afac179c38db6531123bc1167d65/colcon_ros/task/ament_cmake/build.py#L50-L53
