### ISSUE TITLE
Cross-compiling ROS 2 workspaces - please do not promote building packages in underlays to an error and suggestion

### ISSUE THREAD

**Issue by vmayoral** [colcon/colcon-core#469]
After updating colcon to latest releases I observed the following:

```bash
colcon build --merge-install
[1.454s] WARNING:colcon.colcon_core.verb:Some selected packages are already built in one or more underlay workspaces:
	'ament_cppcheck' is in: /opt/ros/rolling
	'ament_lint' is in: /opt/ros/rolling
	'ament_lint_auto' is in: /opt/ros/rolling
	'ament_uncrustify' is in: /opt/ros/rolling
	'image_geometry' is in: /opt/ros/rolling
	'ament_flake8' is in: /opt/ros/rolling
	'ament_pep257' is in: /opt/ros/rolling
	'ament_copyright' is in: /opt/ros/rolling
	'ament_cpplint' is in: /opt/ros/rolling
	'ament_lint_cmake' is in: /opt/ros/rolling
	'ament_xmllint' is in: /opt/ros/rolling
	'launch' is in: /opt/ros/rolling
	'ament_cmake_lint_cmake' is in: /opt/ros/rolling
	'launch_testing' is in: /opt/ros/rolling
	'launch_xml' is in: /opt/ros/rolling
	'launch_yaml' is in: /opt/ros/rolling
	'ament_cmake_copyright' is in: /opt/ros/rolling
	'ament_cmake_cppcheck' is in: /opt/ros/rolling
	'ament_cmake_cpplint' is in: /opt/ros/rolling
	'ament_cmake_flake8' is in: /opt/ros/rolling
	'ament_cmake_pep257' is in: /opt/ros/rolling
	'ament_cmake_uncrustify' is in: /opt/ros/rolling
	'ament_cmake_xmllint' is in: /opt/ros/rolling
	'launch_testing_ament_cmake' is in: /opt/ros/rolling
	'ament_lint_common' is in: /opt/ros/rolling
	'cv_bridge' is in: /opt/ros/rolling
	'image_transport' is in: /opt/ros/rolling
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding ament_cmake_copyright ament_cmake_cppcheck ament_cmake_cpplint ament_cmake_flake8 ament_cmake_lint_cmake ament_cmake_pep257 ament_cmake_uncrustify ament_cmake_xmllint ament_copyright ament_cppcheck ament_cpplint ament_flake8 ament_lint ament_lint_auto ament_lint_cmake ament_lint_common ament_pep257 ament_uncrustify ament_xmllint cv_bridge image_geometry image_transport launch launch_testing launch_testing_ament_cmake launch_xml launch_yaml

This may be promoted to an error in a future release of colcon-core.
```

This is the exact behavior we're currently using in the Hardware Acceleration Working Group (HAWG) for cross-compilation. The use case for us is clear, we're cross-compiling packages that exist in underlays to other (compute) architectures. Seing this warning is already a bit annoying but turning it into an error would break things completely for us so please do not.

Currently, the options available to mitigate this are:

```bash
  --allow-overriding PKG_NAME [PKG_NAME ...]
                        Allow building packages that exist in underlay workspaces
```

Would you be open to a new flag `--allow-overriding-all` that directly ignores and allows building **all** packages regardless of whether they're already present in underlays?

If you confirm this is of interest, I'm happy put a few cycles to code it. I'd love to have this for Humble. With this new flag, we'd be able to create `mixins` that integrate it directly to further simplify user's flow.

**Comment by mnissov** [comment]
Experiencing the same problem here, same as the OP. Current warning is annoying, but the foreshadowed error would be very disruptive.

**Comment by sloretz** [comment]
There's a discussion about this in #465.

**Comment by sloretz** [comment]
> The more common approach for cross-compilation is to simply extend the CMake project by setting the appropriate environment. This can be done manually in the CMakeLists.txt or for the whole workspace (e.g. by using mixins). To give you an example, here

@vmayoral I see from [this architecture diagram](https://github.com/ros-acceleration/community#architecture) three commands

```
colcon build --merge-install
source install/setup.bash
colcon build --merge-install --mixin kv260  --install-dir install-kv260 --build-dir build-kv260
```

Does that mean the same workspace is built, sourced, then built again? If so, would you be willing to check if #473 fixes this issue?

I also see the warning message says the projects were found in `/opt/ros/rolling`. Is `/opt/ros/rolling` sourced too? Is that required for cross compiling, or caused by something else like `source /opt/ros/...` being in the `.bashrc`?

**Comment by vmayoral** [comment]
> Does that mean the same workspace is built, sourced, then built again? If so, would you be willing to check if #473 fixes this issue?

@sloretz gave it a try. Unfortunately, it doesn't. I debugged things a bit and indeed `prefix_path` and `install_base` don't match (e.g. `prefix_path=/home/xilinx/ros2_ws/install` and `install_base=/home/xilinx/ros2_ws/install-kv260`). Note that we're invoking the cross-compilation as follows:

```bash
colcon build --build-base=build-kv260 --install-base=install-kv260 --merge-install --mixin kv260 --packages-select <whatever>
```

The rationale behind this is covered at [REP-2008 PR](https://github.com/ros-infrastructure/rep/pull/324) but in a nutshell, workspace overlays are used to abstract things away from the workstation environment, all the way into the resulting cross-compiled overlay targeting the hardware accelerator. 

> I also see the warning message says the projects were found in /opt/ros/rolling. Is /opt/ros/rolling sourced too? Is that required for cross compiling, or caused by something else like source /opt/ros/... being in the .bashrc?

That's part of the recommended dev. environment, to align with common ROS setups. Maybe the following diagram helps:

```
/home/xilinx/ros2_ws/install-kv260    ------> 3. top overlay, destination of the cross-compiled artifacts for KV260
    /home/xilinx/ros2_ws/install      ------> 2. middle overlay, helps prepare ROS build env. for cross-compilation
        /opt/ros/rolling              ------> 1. base overlay, default ROS 2 installation in the workstation
```

while maintaining the first two overlays, the top one can change across hardware targets (`ultra96v2`, `zcu102`, `jetson`, etc).

Let me know if you guys are working on this or if you'd like a patch that addresses our use case as suggested above.

**Comment by vmayoral** [comment]
Ping @methylDragon, this is one of the things that would be awesome to expedite as well. It's leading to very verbose and ugly build processes.

**Comment by methylDragon** [comment]
I am working on reviewing the PR for one of the blockers to getting this fixed.
https://github.com/colcon/colcon-installed-package-information/pull/1

**Comment by vmayoral** [comment]
Has this issue been fully addressed @cottsay and @sloretz?

I tried reproducing https://github.com/colcon/colcon-override-check/pull/1#pullrequestreview-903380819 but branches have been removed:

<details>

```bash
vcs import . --recursive < colcon.repos
E...........E.......E...
=== ./colcon-argcomplete (git) ===
Cloning into '.'...

=== ./colcon-bash (git) ===
Cloning into '.'...

=== ./colcon-cd (git) ===
Cloning into '.'...

=== ./colcon-cmake (git) ===
Cloning into '.'...

=== ./colcon-core (git) ===
Cloning into '.'...

=== ./colcon-defaults (git) ===
Cloning into '.'...

=== ./colcon-devtools (git) ===
Cloning into '.'...

=== ./colcon-installed-package-information (git) ===
Could not checkout ref 'cottsay/implement': fatal: invalid reference: cottsay/implement
=== ./colcon-library-path (git) ===
Cloning into '.'...

=== ./colcon-metadata (git) ===
Cloning into '.'...

=== ./colcon-mixin (git) ===
Cloning into '.'...

=== ./colcon-notification (git) ===
Cloning into '.'...

=== ./colcon-output (git) ===
Cloning into '.'...

=== ./colcon-override-check (git) ===
Could not checkout ref 'cottsay/implement': fatal: invalid reference: cottsay/implement
=== ./colcon-package-information (git) ===
Cloning into '.'...

=== ./colcon-package-selection (git) ===
Cloning into '.'...

=== ./colcon-parallel-executor (git) ===
Cloning into '.'...

=== ./colcon-pkg-config (git) ===
Cloning into '.'...

=== ./colcon-powershell (git) ===
Cloning into '.'...

=== ./colcon-python-setup-py (git) ===
Cloning into '.'...

=== ./colcon-recursive-crawl (git) ===
Cloning into '.'...

=== ./colcon-ros (git) ===
Could not checkout ref 'cottsay/ament-index-deps': fatal: invalid reference: cottsay/ament-index-deps
=== ./colcon-test-result (git) ===
Cloning into '.'...

=== ./colcon-zsh (git) ===
Cloning into '.'...

```
</details>

Let me know how can I validate this please.

**Comment by methylDragon** [comment]
`colcon-override-check` and `colcon-installed-package-information` implementations have been merged into `main`. You can checkout the tip of `main` for those, and it should work.

**Comment by methylDragon** [comment]
![image](https://user-images.githubusercontent.com/20265670/158434628-f67e2061-b178-41e1-98ea-312a7595f28e.png)

(:

**Comment by vmayoral** [comment]
> Can't we just implement something like --allow-overriding-all and avoid having the user to specify every single package, every single time? 

Happy to help with it if needed, as pointed out above. Ideally, this should get implemented using an environmental variable which allows the python logic to pick it every time to set it off completely and across builds. E.g.:

```bash
export ROS_ALLOW_OVERRIDING_ALL=1
```

**Comment by sloretz** [comment]
> Can't we just implement something like --allow-overriding-all and avoid having the user to specify every single package, every single time?

The warning has been moved to a separate package `colcon-override-warning` so it can be gotten rid of completely by uninstalling it. See https://github.com/colcon/colcon-common-extensions/pull/15 which only recommends the new package.

**Comment by vmayoral** [comment]
Thanks, I'll have a look at these two pointers.
