### ISSUE TITLE
--log-base /dev/null doesn't seem to work

### ISSUE THREAD

**Issue by icolwell-as** [colcon/colcon-core#479]
- Ubuntu 20.04 
- Noetic/Foxy
- colcon-core 0.7.1
- colcon-output 0.2.12

According to the documentation found [here](https://colcon.readthedocs.io/en/released/reference/global-arguments.html), you should be able to do something like this:

```
colcon --log-base /dev/null build
```
However when I try that I get the following error no matter what package I try to compile:
```
ERROR:colcon.colcon_core.event_reactor:Exception in event handler extension 'log': unsupported operand type(s) for /: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/event_reactor.py", line 78, in _notify_observers
    retval = observer(event)
  File "/usr/lib/python3/dist-packages/colcon_output/event_handler/log.py", line 80, in __call__
    base_path = get_log_directory(job)
  File "/usr/lib/python3/dist-packages/colcon_output/event_handler/log.py", line 166, in get_log_directory
    return get_log_path() / job.identifier
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

I found this issue that reports a similar but different issue with the same test case (`--log-base /dev/null`):
https://github.com/colcon/colcon-core/issues/263

Does anyone know of a work-around? I tried `COLCON_LOG_PATH` environment variable but it results in the same error.

**Comment by cottsay** [comment]
This is solved by colcon/colcon-output#39, which hasn't been released yet.
