### ISSUE TITLE
AppVeyor won't go away

### ISSUE THREAD

**Issue by cottsay** [colcon/colcon-core#481]
It appears that removing the AppVeyor configuration and removing the webhook to trigger it still isn't enough to stop AppVeyor from reporting build failures in CI. Access could be revoked at the organization level, but I'm not sure every single extension has been fully migrated, particularly the ones which haven't been touched for some time.

@dirk-thomas - do you have the capability in AppVeyor itself to disable the builds?

**Comment by dirk-thomas** [comment]
Sorry, I don't read GitHub notifications on a regular basis anymore. I just logged into AppVeyor and deleted the `colcon-core` project there. I hope that helps :crossed_fingers:

**Comment by cottsay** [comment]
I'll keep an eye on the next commits to master. Thanks for taking care of it!
