### ISSUE TITLE
Colcon build shows nothing

### ISSUE THREAD

**Issue by epicjung** [colcon/colcon-core#489]
When I run colcon build --log-level 10, I get this output:

![image](https://user-images.githubusercontent.com/38877956/156518615-8b62fb0e-fa7c-4005-8517-28074ddb98fe.png)

It stops there and does not build afterward. 

Please help.

Thank you in advance.

**Comment by cottsay** [comment]
When you hit Ctrl-C to exit, do you get a backtrace?

**Comment by cottsay** [comment]
Hi @epicjung, were you able to resolve this issue?

**Comment by cottsay** [comment]
Hearing nothing from @epicjung for 2 months, I'm going to close this issue.

If someone is able to reproduce this problem, please re-open this issue so we can work to solve it.
