### ISSUE TITLE
Support comments in .dsv files

### ISSUE THREAD

**Issue by jacobperron** [colcon/colcon-core#492]
Supporting comments would be useful for documenting the contents of .dsv files as well as during development (e.g. temporarily commenting out a line).

I don't feel strongly about syntax, though using the number sign (`#`) seems reasonable since it is familiar with users of Bash and Python.

If we add support for comments, we should document the feature [here](https://colcon.readthedocs.io/en/released/developer/environment.html#dsv-files).

**Comment by cottsay** [comment]
I can only assume that `.dsv` is meant to represent "Delimiter-separated values", but I can't find any design documentation on this feature from when it was originally implemented.

Some prevalent DSV files used on *nix are `/etc/passwd` (and family) and `/etc/inittab`. The `passwd` family doesn't have widespread support for comments, but `inittab` seems to support `#` for comments, which seems reasonable to me.

If we move forward with comment support, it will need to be added to `ament_package` as well.
