### ISSUE TITLE
ament_cmake_python Support?

### ISSUE THREAD

**Issue by danzimmerman** [colcon/colcon-core#524]
The ROS2 docs describe a build type of `ament_cmake_python` where you can mix `ament_cmake` and `ament_python` builds in a single package:

https://docs.ros.org/en/humble/How-To-Guides/Ament-CMake-Python-Documentation.html#using-ament-cmake-python

If I try to follow along there, I get a warning:

```
[0.454s] colcon.colcon_core.verb WARNING No task extension to 'build' a 'ros.ament_cmake_python' package
```
and it doesn't seem like the package gets processed correctly.

I'm wondering if this type of package is actually supported at this time? Is there an extra Colcon package I need to install? 

I'm running `colcon-common-extensions` version `0.3.0`. Apologies if this is the wrong repo to raise this issue.

**Comment by christophebedard** [comment]
> https://docs.ros.org/en/humble/How-To-Guides/Ament-CMake-Python-Documentation.html#using-ament-cmake-python

As mentioned at the very top of that page, `ament_cmake_python` is not a build type:

> `ament_cmake_python` is a package that provides CMake functions for packages of the `ament_cmake` build type that contain Python code.

Your package should still be an `ament_cmake` package, i.e., your `package.xml` should contain `<build_type>ament_cmake</build_type>`. You can use `ament_cmake_python` as shown on the `ament_cmake_python` user documentation page.

**Comment by danzimmerman** [comment]
Thanks, closing for lack of reading comprehension.
