### ISSUE TITLE
Unknown build package generated when using virtual environment

### ISSUE THREAD

**Issue by dswasey9608** [colcon/colcon-core#526]
Hello! I am new to using `colcon`, and I am using it to work with ROS2. I am working with ROS2 Humble

I have been working on installing some packages from someone I inherited some work from, and in going through the installation process I have noticed something I don't quite understand.

For containment of package installations, I am using a virtual environment. I started in a new workspace with ROS2 packages that haven't been built yet, with a virtual environment made simply by running

`python -m venv --system-site-packages venv`

I have found that running `colcon build` in the active virtual environment in the top-level directory of my ROS workspace generates files for a mystery package called `my-test-package`. This is not a package in any of the folders I cloned. Looking at the files, it doesn't seem to be anything that will impact my use of the other ROS2 packages that are in the `src` directory.

After doing some testing, I found that the virtual environment folder just needs to exist in the same folder that `colcon build` is run, not even activated, and this extra `my-test-package` will show up. This was tested after removing the previous `build`, `install`, and `log` folders. Going even further, I tried the same thing in a new test workspace with absolutely nothing else in it besides the `venv` folder and got the same result. Cleaning the workspace then running `colcon build` again (without the `venv` folder) will not generate the `my-test-package`.

Here is some terminal output when building from a workspace with a virtual environment folder (notice I didn't activate the virtual environment):
```
~/code/test_ws$ rm -rf *
~/code/test_ws$ python -m venv --system-site-packages venv
~/code/test_ws$ colcon build
Starting >>> my-test-package
--- stderr: my-test-package                   
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
Finished <<< my-test-package [0.73s]

Summary: 1 package finished [1.19s]
  1 package had stderr output: my-test-package
```

And here is what happens when the virtual environment folder isn't there:
```
~/code/test_ws$ rm -rf *
~/code/test_ws$ ls
~/code/test_ws$ colcon build
                     
Summary: 0 packages finished [0.15s]

```
Having other folders like `src` does not result in building the `my-test-package` package as long as the `venv` folder is not there.

I can't find any reasons for this behavior in the documentation for `colcon` or for ROS2. if there is a reason, it would be nice to be able to read about it in the documentation somewhere. It isn't critical, it is just a strange behavior that I don't quite understand.

Thanks!

**Comment by cottsay** [comment]
If not otherwise specified, the default crawl target for colcon's search for packages is the current working directory, not `src`. Here's where that's specified: https://github.com/colcon/colcon-recursive-crawl/blob/0cd20abe4b7d620a57a5995f034e8567b8414fdc/colcon_recursive_crawl/package_discovery/recursive_crawl.py#L33-L38

During typical use, colcon doesn't crawl the `build` or `install` subdirectories of the workspace because when they're created, they're specifically marked with `COLCON_IGNORE` files.

You could either:
1. Create a `COLCON_IGNORE` marker file in the root of your `venv` so that colcon doesn't crawl it for packages.
2. Stop putting non-workspace content in your workspace, and put the venv somewhere else.

**Comment by cottsay** [comment]
If my recommendation doesn't resolve your issue, please feel free to reopen this ticket.
