### ISSUE TITLE
Question: how to pass python parameters

### ISSUE THREAD

**Issue by felixf4xu** [colcon/colcon-core#557]
Hi,

When I build a package, it has a warning like 
>DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

I would like to hide it by `python -W ignore::DeprecationWarning`, so how can I pass `-W ignore::DeprecationWarning` to python via colcon?

**Comment by cottsay** [comment]
I don't think colcon currently supports passing additional parameters to the build tool.

For warnings specifically, you should check out the `PYTHONWARNINGS` environment variable.
