### ISSUE TITLE
colcon sometimes doesn't exit after Ctrl+C on Windows

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#58]
Ctrl+C on Windows does interrupt the build of the package being built but then the tool hangs and doesn't exit. Only option is to close the terminal.

**Comment by dirk-thomas** [comment]
> Only option is to close the terminal.

`Ctrl+Break` should stop the running process and keep your terminal around.

**Comment by dirk-thomas** [comment]
Since even with the referenced merged PRs the invocation still sometimes doesn't exit I will keep this ticket open.

**Comment by dirk-thomas** [comment]
Assuming #30 and colcon/colcon-parallel-executor#6 have resolved this issue I am going ahead and close the ticket. Please feel free to comment on the closed issue if this is still a problem for you.
