### ISSUE TITLE
add a flag to colcon build similar to ament_tools `--build-tests`

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#61]
Currently colcon documentation says that to build tests people should:
```
ament: --build-tests
colcon: --cmake-args " -DBUILD_TESTING=1"
```
But `BUILD_TESTING` is ON by default in CTest so if users don't pass the option the tests are built anyway: https://cmake.org/cmake/help/v3.7/module/CTest.html

We could first change the documentaiton to reflect this.
A better (maybe further looking) alternative would be to implement an equivalent to `--build-tests` in colcon. This would allow users to pass a single flags to build the tests of their heterogeneous workspaces (in the case where multiple build systems are involved and all have a different way of specifying test building).

**Comment by dirk-thomas** [comment]
> We could first change the documentaiton to reflect this.

Please create a PR for the proposed change to address the current difference.

> A better (maybe further looking) alternative would be to implement an equivalent to --build-tests in colcon.

Sounds good to me.

**Comment by dirk-thomas** [comment]
A new option to control this sounds good to me. I would rather not change the default though. Why not? Because that is not what a CMake user would expect when not configuring anything different. So an option to disable building tests seems more appropriate to me.

**Comment by mikaelarguedas** [comment]
should the behavior of the tool change (topological order, something else)?

e.g. `test_depends` would be removed from the dependency list of the package if the flag disabling test compilation is not provided

**Comment by mikaelarguedas** [comment]
I would like to bump the priority of this item.

>  It might confuse users though if the set of packages they selected changes based on the option being toggled.

I currently have a use case where this is the behavior I want to exercise:
- One of the test dependencies of my packages cannot build on the platform I'm using
- I want to build my workspace without tests so I don't *need* that dependency
- I run `colcon build --packages-skip my_missing_test_depend --cmake-args -DBUILD_TESTING=OFF`
- My build fails with the following error message:
```
colcon.colcon_cmake.task.cmake.build ERROR Failed to find the following files:
- C:\dev\ros2\install\share\my_missing_testing_dep\package.bat
Check that the following packages have been built:
- my_missing_testing_dep
```

Currently the only way to work around the issue is to remove the dependency from the package.xml of all the packages having that test dependency.
Having the `--build-tests` flag modify the list of required dependencies passed to each task would be valuable.

Does that sound reasonable?

**Comment by dirk-thomas** [comment]
> My build fails with the following error message:

A package which is "skipped" during the build is still considered to be present (and assumed to be built previously). What you want is to "ignore" that package as if it isn't even present in the workspace (or has a `COLCON_IGNORE marker). You should be able to achieve this with the following option: `--packages-ignore my_missing_test_dep`

**Comment by mikaelarguedas** [comment]
Oh good to know I forgot an ignore option was available :+1:

Then it can stay as an enhancement.

I still believe that a feature of this option (when not exercised) would be to demote test dependencies from the dependency list allowing people to not build their test dependencies when they decide to not build the tests

**Comment by dirk-thomas** [comment]
> I still believe that a feature of this option (when not exercised) would be to demote test dependencies from the dependency list allowing people to not build their test dependencies when they decide to not build the tests

I see a "problem" with considering a test dependency a dependency in one build but not in another: basically the result of your build can become non-deterministic. When you do just one build with tests enabled the behavior might be different than a build which happens after a previous build was done without test dependencies (e.g. cached information in the CMakeCache.txt from previous run with different environment).

**Comment by dirk-thomas** [comment]
With the new `mixin` feature available this could be addressed by adding a new "recipe" to the [mixin repository](https://github.com/colcon/colcon-mixin-repository/), e.g.

```
"build-tests": {
    "build": {
        "cmake-args": ["-DBUILD_TESTING=1"]
    }
}
```

I am just not sure about the naming of the mixin...

**Comment by mikaelarguedas** [comment]
The build-testing mixins look good to me to be able to toggle the arguments.

> I am just not sure about the naming of the mixin...

`build-testing` seems fine for now :+1:

> I see a "problem" with considering a test dependency a dependency in one build but not in another: basically the result of your build can become non-deterministic. When you do just one build with tests enabled the behavior might be different than a build which happens after a previous build was done without test dependencies (e.g. cached information in the CMakeCache.txt from previous run with different environment).

I understand the concern. What would be a recommended alternative to ignore all the dependencies listed as test_depend in a workspace? (basically building all packages up to foo but removing the ones that are only `test_depend` in the chain)

**Comment by dirk-thomas** [comment]
Since mixins for this flag have been added in colcon/colcon-mixin-repository#2 I will go ahead and close this.
