### ISSUE TITLE
 colcon list Traceback (most recent call last):   File "/usr/bin/colcon", line 33, in <module>     sys.exit(load_entry_point('colcon-core==0.16.0', 'console_scripts', 'colcon')())   File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 118, in main     return _main(command_name=command_name, argv=argv)   File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 185, in _main     create_log_path(args.verb_name)   File "/usr/lib/python3/dist-packages/colcon_core/location.py", line 186, in create_log_path     os.makedirs(str(path))   File "/usr/lib/python3.10/os.py", line 225, in makedirs     mkdir(name, mode) PermissionError: [Errno 13] Permission denied: 'log/list_2024-04-06_02-45-22'

### ISSUE THREAD

**Issue by yst-one** [colcon/colcon-core#634]
colcon list
Traceback (most recent call last):
  File "/usr/bin/colcon", line 33, in <module>
    sys.exit(load_entry_point('colcon-core==0.16.0', 'console_scripts', 'colcon')())
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 118, in main
    return _main(command_name=command_name, argv=argv)
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 185, in _main
    create_log_path(args.verb_name)
  File "/usr/lib/python3/dist-packages/colcon_core/location.py", line 186, in create_log_path
    os.makedirs(str(path))
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'log/list_2024-04-06_02-45-22'

**Comment by cottsay** [comment]
You don't have write permission to your working directory and colcon is trying to write a log file there.

To disable logging so that you can invoke `colcon list` in that directory, run `colcon --log-base /dev/null list`

**Comment by christophebedard** [comment]
This can happen if you run `sudo colcon ...` and then run `colcon`. In that case, try removing the directory using `rm -rf log`.

**Comment by cottsay** [comment]
With no response from the issue author for months, I'm going to assume this issue has been resolved. Please feel free to re-open if the problem persists.
