### ISSUE TITLE
Create repository for colcon-ros-gradle

### ISSUE THREAD

**Issue by esteve** [colcon/colcon-core#77]
In the same way that `colcon-cmake` is for pure CMake projects and `colcon-ros` include CMake-based ROS projects, I'd like to have a separate `colcon-ros-gradle` repository for building ROS projects that use ament Gradle plugin (https://plugins.gradle.org/plugin/org.ros2.tools.gradle)

Thanks.

**Comment by dirk-thomas** [comment]
I created the [repo](https://github.com/colcon/colcon-ros-gradle) and added you as an admin collaborator.

Related to #40.

**Comment by esteve** [comment]
@dirk-thomas thanks!
