### ISSUE TITLE
Better error msg if compile-time Python not found at sourcing time on Windows

### ISSUE THREAD

**Issue by mikaelarguedas** [colcon/colcon-core#85]
Since https://github.com/colcon/colcon-core/pull/70 we use Python to source packages in topological order.
If the python executable is not found it crashes with `The system cannot find the path specified.`

We should provide a better error message so that users know what fails.

One way to do it might be to check that the file exist before calling it. But it may be to expensive...

**Comment by dirk-thomas** [comment]
> One way to do it might be to check that the file exist before calling it. But it may be to expensive...

That sounds good and is certainly not too expensive. Each recusrively sourced script is checked for existence before so one extra check won't be significant. Please consider to create a pull request for the additional check.
