### ISSUE TITLE
python3-colcon `colcon build` reports an error on Ubuntu Xenial

### ISSUE THREAD

**Issue by paulbovbel** [colcon/colcon-core#90]
`colcon build` on an ubuntu:xenial container reports the following error:

```
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.package_identification.python': No module named 'setuptools.config'
```

It looks like the system packaged `setuptools` doesn't include this module in xenial - this can be worked around by upgrading the system `setuptools` using `sudo python3 -m pip install setuptools -U`.

**Comment by dirk-thomas** [comment]
Can you clarify which instructions you followed for building the package. The [documentation](https://colcon.readthedocs.io/en/latest/developer/bootstrap.html) mentions that updating `setuptools` might be necessary.

**Comment by sloretz** [comment]
It looks like `setuptools.config` was added in [`30.3.0`](https://github.com/pypa/setuptools/commit/7df349d07e6441a33427ad5c371f12bf6bedc529#diff-360050608fe825a457c8093298edf207). Would chainging the [`install_requires` for setuptools](https://github.com/colcon/colcon-core/blob/dff8696a2c17c9c353f919f7733395ca021a6c00/setup.cfg#L39) to `setuptools >= 30.3.0` cause it to be upgraded when `colcon-core` is installed via pip?

**Comment by dirk-thomas** [comment]
For Debian packages there is no way for the `colcon` Debian package to fix the problem / install the newer `setuptools` version automatically. But #91 ensures for `pip` installed packages that the dependency is new enough as well as prints a better error message in the Debian case where the dependency is too old.
