### ISSUE TITLE
Get task helper functions are hardcoded with __name__

### ISSUE THREAD

**Issue by matmur** [colcon/colcon-core#97]
Task helper functions `get_task_extension` and `get_task_extensions` use `__name__` which means all task extension searches use the prefix `colcon_core.task`. If I want to define a verb in another package (eg. `my_package.verb.my_verb`), then this breaks the task lookup, since the tasks for this new verb should be registered under `my_package.task.my_verb` (based on my understanding of the colcon conventions).

I think the simplest way to fix this would be to pass in the group name (this is named from the parameter in `instantiate_extensions`) instead of the task name. Right now `test` and `build` are passed in for the test and build verbs. Instead they would pass in `colcon_core.task.test` and `colcon_core.task.build`. The get methods would then no longer create the group name. This would affect `add_task_arguments` which would also need to take in the group name.

Is there a more elegant solution than this? Perhaps it would be better to pass in the module name and let the function generate the group name string from that + 'task' + `task_name`?

I'll be happy to make a pull request with a fix once I get the go-ahead on the implementation.

**Comment by dirk-thomas** [comment]
Thanks for bringing this limitation up. That should certainly be supported.

Please see #98 which aims to support the described use case and let me know if it works for you.

**Comment by matmur** [comment]
Looks good to me, my verb works with the updated methods. Thanks for the support!
